# content.py
ROADMAP_DATA = {
    "Stage 1": {
        "title": "Foundation",
        "duration": "Months 1–3",
        "goal": "Build a deep intuition for market mechanics and the quant research cycle.",
        "overview": "Before writing a single line of code, you must understand the 'physics' of the markets. This stage is about moving from a retail mindset (guessing direction) to a quantitative mindset (analyzing probabilities and market structure).",
        "topics": [
            {
                "category": "Market Microstructure (The 'Physics' of Trading)",
                "items": [
                    "**The Limit Order Book (LOB):** To understand price action, we must first master the Limit Order Book—the central engine of modern exchanges. You need to distinguish between 'makers' (passive liquidity providers who place limit orders) and 'takers' (aggressive participants who cross the spread with market orders). A professional understanding involves recognizing how 'order imbalance' at specific price levels creates the momentum or resistance that drives the 'mid-price' higher or lower. We don't just look at price; we look at the 'queue' of intention that precedes it.",
                    "**Liquidity & Slippage:** In the academic sense, liquidity is the ability to trade significant volume without significantly impacting the price. As a quant, you must model 'Slippage' as a direct cost of doing business. When you 'cross the spread,' you are paying for immediate execution. If the LOB is 'thin,' your large order will walk up or down the book, eating through price levels and resulting in a worse average fill price than what was displayed on your screen.",
                    "**Market Participants:** Financial markets are a zero-sum ecosystem of diverse actors. You must identify the 'footprint' of each: Market Makers (who profit from the spread and provide stability), High-Frequency Traders (who exploit micro-latencies), Institutional Flow (pension funds and ETFs moving massive size over days), and Retail Traders (who often provide the liquidity that professionals harvest).",
                    "**Asset Class Mechanics:** Not all markets are created equal. Equities represent ownership; Futures are contracts for future delivery with embedded leverage and 'basis' risk; Options are non-linear bets on volatility (the 'Greeks'). You must understand the settlement cycles (T+2), margin requirements, and the underlying fundamental drivers of each before attempting to model them."
                ]
            },
            {
                "category": "The Quantitative Philosophy",
                "items": [
                    "**Alpha vs. Beta:** This is the most fundamental distinction in finance. 'Beta' is the return you get simply for being in the market (e.g., the S&P 500 going up). 'Alpha' is the excess return generated by your specific skill or strategy after adjusting for risk. A true quant seeks 'Pure Alpha'—returns that are uncorrelated with the broader market, allowing you to profit even when the world is in a recession.",
                    "**Expected Value (EV) & Ergodicity:** We think in probabilities, not certainties. Every trade is a draw from a distribution. Your 'Edge' is a positive Expected Value (EV = [Win % × Avg Win] - [Loss % × Avg Loss]). However, you must also understand 'Ergodicity'—even a strategy with positive EV can lead to 'ruin' if you over-leverage and hit a single bad streak. We manage for survival first, profit second.",
                    "**The 4-Stage Research Lifecycle:** A professional quant lab operates with academic rigor. It begins with **Data Ingestion** (ensuring high-fidelity, clean inputs), followed by **Alpha Research** (forming a falsifiable hypothesis), then **Backtesting** (verifying the hypothesis against historical 'unseen' data), and finally **Execution** (deploying to a live environment with real-time risk monitoring). Skipping any step is a recipe for catastrophic failure."
                ]
            }
        ],
        "guide": [
            "1. <b>Study the Tape:</b> Open a platform like TradingView or ThinkOrSwim and watch the Level 2 (Depth of Market) for 30 minutes. Notice how big orders 'absorb' price.",
            "2. <b>Read 'Market Wizards':</b> Understand the psychological transition from 'gambling' to 'process-oriented' trading.",
            "3. <b>Learn the Lingo:</b> Define every term in the LOB: Bid-Ask Spread, Mid-price, Depth, and Imbalance."
        ],
        "exercise": "<b>The Spread Analysis:</b> Download 1 day of 1-minute OHLCV data for SPY. In Excel, calculate the average candle size. Research what the typical bid-ask spread is for SPY. Calculate what percentage of your 'candle' is eaten by the spread.",
        "milestone": "🎯 Complete the 'Financial Markets 101' certification and explain the LOB to someone who doesn't trade.",
        "resources": [
            "📖 Market Wizards — Jack Schwager",
            "📖 Quantitative Trading — Ernest Chan (Chapters 1-2)",
            "🎓 CME Group: Introduction to Futures"
        ]
    },
    "Stage 2": {
        "title": "Mathematics & Statistics",
        "duration": "Months 3–6",
        "goal": "Equip yourself with the statistical tools to separate signal from noise.",
        "overview": "Finance is 'noisy'. Most patterns you see are just random chance. This stage teaches you the 'Bullshit Detector'—the mathematical rigorousness required to prove an edge exists.",
        "topics": [
            {
                "category": "Probability & Distributions (The Foundation of Signal)",
                "items": [
                    "**The Normal Distribution Fallacy:** Most introductory finance courses assume that returns follow a 'Bell Curve' (Normal Distribution). In the real world, markets exhibit 'Fat Tails' (Excess Kurtosis) and 'Skewness'. This means 'Six-Sigma' events (crashes like 1987 or 2008) happen thousands of times more often than the theory predicts. A quant's job is not to assume normality, but to build models that survive its inevitable breakdown.",
                    "**The Logic of Log-Returns:** We do not model simple percentage changes ($ (P_t - P_{t-1}) / P_{t-1} $) because they are not additive over time and are asymmetric (a 50% loss requires a 100% gain to break even). Instead, we use Log-Returns ($ \\ln(P_t / P_{t-1}) $), which allow for time-series additivity and assume a more theoretically sound 'Log-Normal' distribution of prices.",
                    "**Conditional Probability & Bayesian Updating:** The market is not a static game. As new data (price action, earnings, news) arrives, you must update your prior beliefs. Bayesian Statistics provides the framework for this: moving from a 'Prior' probability to a 'Posterior' one. We don't ask 'What will happen?'; we ask 'Given what just happened, what is the new probability of X?'"
                ]
            },
            {
                "category": "Econometrics & Time Series (Detecting Structure)",
                "items": [
                    "**Stationarity & The Unit Root Problem:** You cannot run a regression on raw prices because they are 'non-stationary'—they drift and have infinite variance over time. This leads to 'Spurious Regression' (finding patterns where none exist). We must transform data into stationary series (like returns) where the mean and variance are stable, allowing for valid statistical inference.",
                    "**Cointegration (The Basis of Stat Arb):** While two stocks may drift apart individually, they may be 'cointegrated'—meaning a linear combination of them is stationary. Think of a drunk man walking a dog on a leash; they both wander randomly, but they never stay too far apart. Detecting this 'leash' is how we build Mean Reversion and Pairs Trading strategies.",
                    "**Hypothesis Testing & The P-Value Trap:** In this lab, we demand statistical significance. A 'good-looking' backtest is meaningless unless you can prove the result isn't due to random chance. You must master T-stats, P-values, and the 'Multiple Testing Problem'—if you test 100 random ideas, 5 will look good by pure luck. We use the Bonferroni correction and other methods to filter out these 'false discoveries'."
                ]
            }
        ],
        "guide": [
            "1. <b>Master the Histogram:</b> Plot the returns of Bitcoin vs. S&P 500. Observe the 'kurtosis' in Bitcoin—the extreme outliers.",
            "2. <b>Linear Algebra Basics:</b> Understand how matrices represent portfolios (Weights × Returns).",
            "3. <b>Statistical Significance:</b> Learn why a Sharpe Ratio of 1.0 requires at least 3 years of data to be statistically valid."
        ],
        "exercise": "<b>Statistical Arbitrage Setup:</b> Pick two related stocks (e.g., KO and PEP). Use a simple spreadsheet or Python to plot their price ratio over 1 year. Identify 'mean-reverting' periods where the ratio stretched too far.",
        "milestone": "🎯 Pass the 'Statistics for Finance' module and build a spreadsheet that calculates Z-Scores for any price series.",
        "resources": [
            "📖 Statistics — Freedman, Pisani & Purves",
            "🎓 MIT 18.650: Statistics for Applications",
            "📖 Analysis of Financial Time Series — Ruey Tsay"
        ]
    },
    "Stage 3": {
        "title": "Programming & Data",
        "duration": "Months 6–9",
        "goal": "Build a professional-grade research environment using Python.",
        "overview": "A quant is only as good as their data and their ability to manipulate it. This stage transitions you from manual analysis to automated, vectorized research.",
        "topics": [
            {
                "category": "The Computational Quant Stack",
                "items": [
                    "**The Vectorization Paradigm:** In quantitative programming, 'loops' are your enemy. Python's `for` loops are too slow for processing millions of ticks. You must master **Pandas** and **NumPy** to perform operations across entire arrays simultaneously (Vectorization). This relies on low-level C implementations that are orders of magnitude faster. If you aren't thinking in 'tensors' and 'dataframes,' your research speed will lag behind the market.",
                    "**Scientific Visualization:** A chart is not just a picture; it is a diagnostic tool. You must go beyond simple line plots to master **Interactive Visualization** (Plotly, Bokeh). You need to build tools that allow you to overlay trade executions onto the limit order book, visualize volatility surfaces, and detect 'Look-Ahead Bias' visually by seeing if your signals align with future price action."
                ]
            },
            {
                "category": "Data Engineering & Integrity (The 'GIGO' Principle)",
                "items": [
                    "**ETL Pipelines & Database Architecture:** Garbage In, Garbage Out (GIGO). A professional research lab requires a robust **ETL (Extract, Transform, Load)** pipeline. You must learn to pull data from APIs (Polygon, Alpaca) or flat files (Parquet, HDF5) and store them in a local SQL or NoSQL database. This ensures data persistence and allows you to run complex queries without re-downloading data every time.",
                    "**Survivorship Bias & Point-in-Time Data:** This is where 90% of retail backtests fail. If you only test on stocks that are in the S&P 500 *today*, you are ignoring all the companies that went bankrupt or were delisted (Survivorship Bias). You must learn to build 'Point-in-Time' datasets that represent the market exactly as it looked on any specific day in the past.",
                    "**The Art of Data Cleaning:** Financial data is messy. You will encounter 'bad prints' (erroneous price ticks), missing bars, and corporate actions (Splits, Dividends). You must write robust cleaning algorithms that 'adjust' prices so that a 2-for-1 stock split doesn't look like a 50% crash in your backtest."
                ]
            }
        ],
        "guide": [
            "1. <b>Set up VS Code:</b> Move away from Jupyter for production code. Use a professional IDE with Git integration.",
            "2. <b>Build a Data Loader:</b> Write a script that downloads 5 years of daily data for the NASDAQ 100 and saves it to a Parquet file.",
            "3. <b>Learn Git:</b> Commit your code daily. Use branches for new strategy ideas."
        ],
        "exercise": "<b>The Vectorized Backtester:</b> Build a 10-line Python script using Pandas that calculates the performance of a 'Moving Average Crossover' strategy. No 'if' statements—use only vectorized logic.",
        "milestone": "🎯 Successfully build a local database that auto-updates every night with closing prices for 500 tickers.",
        "resources": [
            "📖 Python for Finance — Yves Hilpisch",
            "💻 'QuantConnect' Bootcamps (Free tutorials)",
            "📖 Python for Data Analysis — Wes McKinney"
        ]
    },
    "Stage 4": {
        "title": "Strategy Building",
        "duration": "Months 9–13",
        "goal": "Research and validate your first institutional-grade trading strategies.",
        "overview": "This is where the magic happens. You will combine market intuition, math, and code to find 'Alpha'—market inefficiencies that you can exploit for profit.",
        "topics": [
            {
                "category": "The Alpha Thesis (The 'Why' of a Strategy)",
                "items": [
                    "**Formulating an Economic Thesis:** Before you write code, you must answer: *Why does this edge exist?* Alpha comes from either **Behavioral Biases** (fear/greed causing overreaction), **Structural Constraints** (forced selling by funds due to mandates), or **Informational Asymmetry** (knowing something before others). If you can't explain your strategy's economic intuition, it is likely just 'overfitted' noise.",
                    "**Factor Models & Risk Premia:** We move beyond single-indicator signals to **Multi-Factor Models**. You must understand the 'Fama-French' factors (Size, Value, Momentum) and learn to decompose your returns. Are you actually generating 'Alpha,' or are you just taking on hidden 'Beta' risk (like exposure to small-cap stocks)?",
                    "**Alternative Data & Signal Combination:** Modern alpha is found in unconventional places: satellite imagery, credit card flows, and **Sentiment Analysis** of news/social media. You must learn to 'clean' these signals and combine them using techniques like **Grinold's Fundamental Law of Active Management** ($ IR = IC \\times \\sqrt{Breadth} $)."
                ]
            },
            {
                "category": "The Backtesting Protocol (Scientific Validation)",
                "items": [
                    "**Modeling Transaction Costs & Market Impact:** A 1% annual edge is easily erased by commissions and slippage. You must learn to build high-fidelity cost models that account for the **Bid-Ask Spread** and 'Market Impact'—the way your own trades push the price against you.",
                    "**Overfitting & The Multiple Testing Bias:** If you torture the data long enough, it will confess to anything. You must learn to detect **P-Hacking** and avoid the 'Backtest Overfitting' trap. We use techniques like **Walk-Forward Analysis** and **Monte Carlo Simulations** to verify that a strategy's performance is robust across different market regimes.",
                    "**Performance Metrics & Risk-Adjusted Returns:** We don't just care about the 'P&L'. You must master the **Sharpe Ratio**, **Sortino Ratio** (focusing on downside risk), and **Maximum Drawdown**. A strategy that makes 20% but drops 40% along the way is 'uninvestable' for most institutional capital."
                ]
            }
        ],
        "guide": [
            "1. <b>Pick a Niche:</b> Don't try to trade everything. Choose one asset (e.g., FX) and one style (e.g., Trend).",
            "2. <b>Write a Strategy Thesis:</b> Before coding, write 1 paragraph explaining *why* this strategy should make money (e.g., 'It exploits the slow reaction of retail to news').",
            "3. <b>Analyze Drawdowns:</b> Look at the 'worst-case' periods. Could you have survived them mentally?"
        ],
        "exercise": "<b>The Alpha Hunt:</b> Research 'The Turn of the Month Effect' or 'The Monday Effect'. Use your Python tools to see if these seasonalities still exist in the S&P 500 today.",
        "milestone": "🎯 Create a 10-page 'Strategy Tear Sheet' including Sharpe, Max Drawdown, Win Rate, and Return Distribution.",
        "resources": [
            "📖 Algorithmic Trading — Ernest Chan",
            "📖 Expected Returns — Antti Ilmanen",
            "🎓 'WorldQuant University' free modules"
        ]
    },
    "Stage 5": {
        "title": "Advanced Quantitative Methods",
        "duration": "Months 13–19",
        "goal": "Master the machine learning and portfolio optimization techniques of top hedge funds.",
        "overview": "At this level, you move beyond simple rules to 'dynamic' models. You will learn how to use ML not for price prediction, but for risk management and signal combination.",
        "topics": [
            {
                "category": "Financial Machine Learning (Beyond Prediction)",
                "items": [
                    "**The Triple Barrier Method & Meta-Labeling:** Traditional ML classification (Buy/Sell) is insufficient for finance. You must master **Marcos López de Prado's** techniques: the 'Triple Barrier' for labeling events and 'Meta-Labeling' to filter out false signals. This allows your model to decide *whether* to take a trade, rather than just predicting direction, significantly improving the 'Precision' of your signals.",
                    "**Feature Engineering & Feature Importance:** A model is only as good as its inputs. You must learn to engineer 'stationary' features from raw order flow, volatility surfaces, and microstructural imbalances. Crucially, you must use **MDA (Mean Decrease Accuracy)** or **SHAP values** to understand *which* features are driving your model and ensure they aren't just memorizing 'noise' from the training set.",
                    "**Purging & Embargoing (Time Series CV):** Standard Cross-Validation fails in finance because of 'Information Leakage' (future data influencing the past via overlapping time series). You must learn to implement **Purged K-Fold Cross-Validation**, which removes data points between training and testing sets to ensure the model is truly generalizing to unseen environments."
                ]
            },
            {
                "category": "Modern Portfolio Construction",
                "items": [
                    "**From Mean-Variance to Hierarchical Risk Parity (HRP):** Traditional Markowitz optimization is 'unstable'—small changes in inputs lead to massive changes in allocations. You must study **Hierarchical Risk Parity (HRP)**, which uses graph theory and machine learning to cluster assets based on correlation and allocate risk more robustly, avoiding the 'concentration risk' of older models.",
                    "**Factor Neutralization & Hedging:** A professional quant doesn't just want to make money; they want to make 'uncorrelated' money. You must learn to **Factor Neutralize** your portfolio—hedging out unwanted exposures to Market, Sector, or Interest Rate risks so that only your 'Pure Alpha' remains. This is how you achieve the 'Holy Grail' of finance: a Sharpe Ratio > 2.0.",
                    "**The Black-Litterman Model:** This is the bridge between market equilibrium and your subjective research views. You must learn to use **Bayesian Inference** to combine the 'Market Cap Weighted' portfolio with your specific alpha signals, allowing for a more stable and theoretically sound allocation than raw optimization."
                ]
            }
        ],
        "guide": [
            "1. <b>Learn Scikit-Learn:</b> Master Random Forests and Gradient Boosting for classification tasks.",
            "2. <b>Study Volatility:</b> Understand 'GARCH' models to forecast when markets will become dangerous.",
            "3. <b>Factor Neutralization:</b> Learn how to hedge out 'Market Risk' so you only profit from your specific alpha."
        ],
        "exercise": "<b>The Regime Detector:</b> Build a K-Means clustering model in Python that categorizes the market into 3 states: 'Low Vol/Bull', 'High Vol/Bear', and 'Sideways/Chop'.",
        "milestone": "🎯 Implement a machine learning model that achieves a 'Precision' of >55% on out-of-sample directional signals.",
        "resources": [
            "📖 Advances in Financial Machine Learning — López de Prado",
            "📖 Options, Futures & Other Derivatives — John Hull",
            "💻 'QuantAcademy' Deep Learning courses"
        ]
    },
    "Stage 6": {
        "title": "Professional Mastery",
        "duration": "Month 19+",
        "goal": "Operate as a full-stack Quant Researcher capable of running institutional capital.",
        "overview": "The final stage is about infrastructure, scale, and longevity. You transition from a 'researcher' to a 'portfolio manager' who manages risk as much as they seek returns.",
        "topics": [
            {
                "category": "Institutional Execution (The 'Plumbing' of Alpha)",
                "items": [
                    "**Algorithmic Execution & Market Impact:** Once you have a signal, you must execute it without 'alerting' the rest of the market. You must learn the mechanics of **VWAP (Volume Weighted Average Price)**, **TWAP (Time Weighted Average Price)**, and **IS (Implementation Shortfall)**. You will build algorithms that 'slice' large orders into thousands of micro-orders to hide your intention from predatory HFT (High-Frequency Trading) bots.",
                    "**OMS/EMS Architecture & Connectivity:** A professional trader doesn't click buttons; they build systems. You must understand the architecture of **Order Management Systems (OMS)** and **Execution Management Systems (EMS)**. You will learn about **FIX Protocol** (Financial Information eXchange) for institutional connectivity and how to manage 'Trade Lifecycle' events, from routing to clearing and settlement.",
                    "**Latency & Infrastructure:** In the world of electronic trading, milliseconds matter. You must learn how to deploy your research stack using **Docker** and **Cloud Infrastructure** (AWS/GCP), and understand the trade-offs of **Colocation**—placing your servers in the same data center as the exchange to minimize signal delay."
                ]
            },
            {
                "category": "The Professional Practice of Quant Finance",
                "items": [
                    "**Tail Risk & Black Swan Management:** A 'good' strategy can be killed by a single 'unprecedented' event. You must learn to model **Tail Risk** and implement hedging strategies (like buying deep out-of-the-money puts) to protect your fund from 'Black Swan' events. We manage for the 1% scenario just as much as the 99% scenario.",
                    "**Capacity Analysis & Alpha Decay:** Alpha is a finite resource. As you manage more capital, your own trading begins to eat your profits. You must learn to perform **Capacity Analysis**—determining the 'AUM' (Assets Under Management) limit of your strategy before it becomes too large to execute. You must also monitor for **Alpha Decay**, recognizing when a market inefficiency has been 'arbitraged away' by competitors.",
                    "**The Ethics & Integrity of Research:** A professional quant is a scientist first. You must maintain a **Research Journal** with academic rigor, documenting every failed experiment and preventing 'Result Mining'. You have a fiduciary duty to your investors and a systemic duty to the market to operate with transparency, ethics, and intellectual honesty."
                ]
            }
        ],
        "guide": [
            "1. <b>Build a Production Pipeline:</b> Use Docker and AWS/GCP to run your research scripts on a schedule.",
            "2. <b>Network:</b> Start contributing to open-source quant libraries or publishing research on SSRN/arXiv.",
            "3. <b>Capital Allocation:</b> Learn the business of quant: how to pitch a strategy to a PM or Seed Fund."
        ],
        "exercise": "<b>The 'Flash Crash' Test:</b> Simulate how your current 'best' strategy would have performed during the 2010 Flash Crash or the 2020 COVID crash. Did it blow up?",
        "milestone": "🎯 Deploy a live 'Paper Trading' portfolio of 3+ diversified strategies and maintain a Sharpe > 1.5 for 6 months.",
        "resources": [
            "📖 Active Portfolio Management — Grinold & Kahn",
            "🎓 'Pioneers in Quantitative Finance' (Documentary/Series)",
            "📖 The Man Who Solved the Market — Gregory Zuckerman"
        ]
    }
}

TRAPS = [
    {"title": "Look-ahead bias", "description": "Using future data in your signals unknowingly."},
    {"title": "Overfitting", "description": "Optimizing parameters until the backtest looks perfect."},
    {"title": "Survivorship bias", "description": "Only testing on stocks that still exist today."},
    {"title": "Ignoring costs", "description": "A 1% annual edge disappears with realistic transaction costs."},
    {"title": "Neglecting regime changes", "description": "A strategy working 2010–2020 may be dead today."}
]

TOOLS_CHECKLIST = {
    "Stage 1-2": ["Excel/Sheets", "Basic Python", "yFinance"],
    "Stage 3-4": ["Pandas", "Zipline/Backtrader", "PostgreSQL", "Git"],
    "Stage 5": ["scikit-learn", "PyTorch/TF", "QuantLib", "Interactive Brokers API"],
    "Stage 6": ["Custom execution infra", "Bloomberg/Refinitiv", "AWS/GCP"]
}
