# content.py

ROADMAP_DATA = {
    "Stage 1": {
        "title": "Foundation",
        "duration": "Months 1–3",
        "difficulty": "Beginner",
        "reading_time": "25h",
        "prereqs": "None",
        "goal": "Build a deep intuition for market mechanics and the quant research cycle.",
        "overview": "Before writing a single line of code, you must understand the 'physics' of the markets. This stage is about moving from a retail mindset (guessing direction) to a quantitative mindset (analyzing probabilities and market structure).",
        "topics": [
            {
                "category": "Market Microstructure (The 'Physics' of Trading)",
                "items": [
                    {"text": "The Limit Order Book (LOB): To understand price action, we must first master the Limit Order Book—the central engine of modern exchanges. You need to distinguish between 'makers' (passive liquidity providers who place limit orders) and 'takers' (aggressive participants who cross the spread with market orders). A professional understanding involves recognizing how 'order imbalance' at specific price levels creates the momentum or resistance that drives the 'mid-price' higher or lower. We don't just look at price; we look at the 'queue' of intention that precedes it.\n\nExample: Imagine AAPL is at $150. If there are 10,000 shares for sale at $150.01 but only 500 shares being bid for at $149.99, the 'depth' is skewed. A small sell order could easily push price down, while a buy order faces a 'wall'.", "is_interview_prep": True},
                    "Liquidity & Slippage: In the academic sense, liquidity is the ability to trade significant volume without significantly impacting the price. As a quant, you must model 'Slippage' as a direct cost of doing business. When you 'cross the spread,' you are paying for immediate execution. If the LOB is 'thin,' your large order will walk up or down the book, eating through price levels and resulting in a worse average fill price than what was displayed on your screen.\n\nExample: You try to buy 5,000 shares of a low-volume penny stock at $1.00. Because there aren't enough sellers at $1.00, your order fills partially at $1.01, $1.02, and $1.05. Your 'slippage' is the difference between your intended $1.00 and your actual $1.03 average fill.",
                    "Market Participants: Financial markets are a zero-sum ecosystem of diverse actors. You must identify the 'footprint' of each: Market Makers (who profit from the spread and provide stability), High-Frequency Traders (who exploit micro-latencies), Institutional Flow (pension funds and ETFs moving massive size over days), and Retail Traders (who often provide the liquidity that professionals harvest).\n\nExample: During a 'Flash Crash,' Market Makers often pull their quotes to avoid toxic flow, leaving only HFTs and desperate sellers, which causes price to 'gap' down vertically.",
                    "Asset Class Mechanics: Not all markets are created equal. Equities represent ownership; Futures are contracts for future delivery with embedded leverage and 'basis' risk; Options are non-linear bets on volatility (the 'Greeks'). You must understand the settlement cycles (T+2), margin requirements, and the underlying fundamental drivers of each before attempting to model them.\n\nExample: In April 2020, WTI Oil futures went to -$37/barrel because the 'physical' storage was full, a mechanic that many purely 'mathematical' quants failed to anticipate."
                ]
            },
            {
                "category": "The Quantitative Philosophy",
                "items": [
                    {"text": "Alpha vs. Beta: This is the most fundamental distinction in finance. 'Beta' is the return you get simply for being in the market (e.g., the S&P 500 going up). 'Alpha' is the excess return generated by your specific skill or strategy after adjusting for risk. A true quant seeks 'Pure Alpha'—returns that are uncorrelated with the broader market, allowing you to profit even when the world is in a recession.\n\nExample: If the market goes up 10% and your portfolio goes up 12%, your 'Beta' return was 10% and your 'Alpha' was 2%. If the market drops 10% and you are flat (0%), you generated 10% Alpha.", "is_interview_prep": True},
                    {"text": "Market Regimes (Trending vs. Mean-Reverting): Markets alternate between periods of directional momentum (Trends) and range-bound oscillation (Mean Reversion). Understanding the 'Regime' is critical because a strategy that works in a trending market will often fail in a sideways market. We use statistical indicators to detect these shifts early.\n\nExample: During a 'Vol-Expansion' regime, trend-following strategies (CTAs) tend to outperform as price 'breaks out'. In a 'Low-Vol' regime, market-making and mean-reversion strategies harvest the range.", "is_interview_prep": True},
                    {"text": "Expected Value (EV) & Ergodicity: We think in probabilities, not certainties. Every trade is a draw from a distribution. Your 'Edge' is a positive Expected Value (EV = [Win % × Avg Win] - [Loss % × Avg Loss]). However, you must also understand 'Ergodicity'—even a strategy with positive EV can lead to 'ruin' if you over-leverage and hit a single bad streak. We manage for survival first, profit second.\n\nExample: A strategy that wins $1,000 99% of the time but loses $1,000,000 1% of the time has a negative EV. You might win for years, but eventually, the 1% will 'wipe you out'.", "is_interview_prep": True},
                    "The 4-Stage Research Lifecycle: A professional quant lab operates with academic rigor. It begins with Data Ingestion (ensuring high-fidelity, clean inputs), followed by Alpha Research (forming a falsifiable hypothesis), then Backtesting (verifying the hypothesis against historical 'unseen' data), and finally Execution (deploying to a live environment with real-time risk monitoring). Skipping any step is a recipe for catastrophic failure.\n\nExample: A researcher finds a 'perfect' strategy but forgot to subtract trading commissions during the Backtesting stage. In live Execution, the strategy loses money every day despite 'looking' profitable."
                ]
            }
        ],
        "guide": [
            "1. <b>Study the Tape:</b> Open a platform like TradingView or ThinkOrSwim and watch the Level 2 (Depth of Market) for 30 minutes. Notice how big orders 'absorb' price.",
            "2. <b>Read 'Market Wizards':</b> Understand the psychological transition from 'gambling' to 'process-oriented' trading.",
            "3. <b>Learn the Lingo:</b> Define every term in the LOB: Bid-Ask Spread, Mid-price, Depth, and Imbalance."
        ],
        "exercise": "<b>The Spread Analysis:</b> Download 1 day of 1-minute OHLCV data for SPY. In Excel, calculate the average candle size. Research what the typical bid-ask spread is for SPY. Calculate what percentage of your 'candle' is eaten by the spread.",
        "milestone": "🎯 Complete the 'Financial Markets 101' certification and explain the LOB to someone who doesn't trade.",
        "common_mistakes": [
            "Confusing price action with market direction: Seeing a candle go up does not mean the market is bullish — check the volume and LOB depth behind it.",
            "Treating all markets identically: The mechanics of a futures contract are fundamentally different from equities. Don't apply equity intuition to FX or commodities without research.",
            "Skipping the microstructure layer: Most retail traders jump straight to indicators. Without understanding who's on the other side of your trade, you are trading blind.",
            "Underestimating transaction costs: A 0.05% per-trade cost sounds tiny but can erase an entire year of alpha in a high-frequency strategy."
        ],
        "quiz": [
            {
                "question": "Which participant type typically provides liquidity by placing limit orders at both the bid and the ask?",
                "options": ["High-Frequency Takers", "Market Makers", "Retail Speculators", "Institutional Buyers"],
                "answer": 1,
                "explanation": "Market Makers profit from the bid-ask spread and provide liquidity by sitting on both sides of the Limit Order Book (LOB)."
            },
            {
                "question": "If you buy 1,000 shares but only 500 are available at your price, and the next 500 are 2 cents higher, what have you experienced?",
                "options": ["Arbitrage", "Alpha", "Slippage", "Basis Risk"],
                "answer": 2,
                "explanation": "Slippage is the difference between your intended price and the actual execution price, usually caused by lack of depth in the LOB."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Market Wizards — Jack Schwager", "url": "https://www.amazon.com/Market-Wizards-Interviews-Top-Traders/dp/1592803377"},
            {"icon": "📖", "name": "Quantitative Trading — Ernest Chan (Ch. 1-2)", "url": "https://www.amazon.com/Quantitative-Trading-Build-Algorithmic-Business/dp/1119800064"},
            {"icon": "🎓", "name": "CME Group: Introduction to Futures", "url": "https://www.cmegroup.com/education/courses/introduction-to-futures.html"},
            {"icon": "🎓", "name": "Yale: Financial Markets (Shiller) — Coursera", "url": "https://www.coursera.org/learn/financial-markets-global"},
            {"icon": "🌐", "name": "Investopedia: Limit Order Book Explained", "url": "https://www.investopedia.com/terms/l/limitorderbook.asp"}
        ]
    },
    "Stage 2": {
        "title": "Mathematics & Statistics",
        "duration": "Months 3–6",
        "difficulty": "Intermediate",
        "reading_time": "45h",
        "prereqs": "Stage 1",
        "goal": "Equip yourself with the statistical tools to separate signal from noise.",
        "overview": "Finance is 'noisy'. Most patterns you see are just random chance. This stage teaches you the 'Bullshit Detector'—the mathematical rigorousness required to prove an edge exists.",
        "topics": [
            {
                "category": "Probability & Distributions (The Foundation of Signal)",
                "items": [
                    "The Normal Distribution Fallacy: Most introductory finance courses assume that returns follow a 'Bell Curve' (Normal Distribution). In the real world, markets exhibit 'Fat Tails' (Excess Kurtosis) and 'Skewness'. This means 'Six-Sigma' events (crashes like 1987 or 2008) happen thousands of times more often than the theory predicts. A quant's job is not to assume normality, but to build models that survive its inevitable breakdown.\n\nExample: On 'Black Monday' in 1987, the S&P 500 dropped 22% in one day. Under a normal distribution, this was a '20-sigma' event, which should only happen once in a trillion years. In reality, market structure makes these 'outliers' much more frequent.",
                    {"text": "The Logic of Log-Returns: We do not model simple percentage changes ($ (P_t - P_{t-1}) / P_{t-1} $) because they are not additive over time and are asymmetric (a 50% loss requires a 100% gain to break even). Instead, we use Log-Returns ($ \\ln(P_t / P_{t-1}) $), which allow for time-series additivity and assume a more theoretically sound 'Log-Normal' distribution of prices.\n\nExample: If a stock goes from $100 to $110 (10% gain) and then back to $100 (9.09% loss), the simple returns don't sum to zero. The log-returns, however, would be $+0.0953$ and $-0.0953$, summing perfectly to zero.", "is_interview_prep": True},
                    {"text": "Conditional Probability & Bayesian Updating: The market is not a static game. As new data (price action, earnings, news) arrives, you must update your prior beliefs. Bayesian Statistics provides the framework for this: moving from a 'Prior' probability to a 'Posterior' one. We don't ask 'What will happen?'; we ask 'Given what just happened, what is the new probability of X?'\n\nExample: You have a 'Prior' belief that a stock is bullish (60% probability). After a surprise earnings beat, you use Bayes' Theorem to update that belief to 80% based on how similar companies reacted to beats in the past.", "is_interview_prep": True}
                ]
            },
            {
                "category": "Mathematics for Quants (The Language of Finance)",
                "items": [
                    {"text": "Linear Algebra for Quants: Matrix operations are the language of modern finance. You must master Vectorized operations for portfolio weights, Eigenvectors for PCA (Principal Component Analysis) to extract risk factors, and Covariance Matrix estimation to understand how assets move together.\n\nExample: Instead of calculating each asset's risk individually, we use matrix multiplication ($ w^T \\Sigma w $) to find the total portfolio variance in a single step.", "is_interview_prep": True},
                    {"text": "Kalman Filters & Adaptive Signal Filtering: Markets are noisy. A Kalman Filter is an optimal estimator that updates its 'belief' about the state of a system as new data arrives. It is widely used in Pairs Trading and tracking the 'Fair Value' of a stock in real-time.\n\nExample: While a Moving Average is slow to react, a Kalman Filter can dynamically adjust its parameters to 'smooth' out noise while remaining highly responsive to a true change in price direction.", "is_interview_prep": True}
                ]
            },
            {
                "category": "Econometrics & Time Series (Detecting Structure)",
                "items": [
                    "Stationarity & The Unit Root Problem: You cannot run a regression on raw prices because they are 'non-stationary'—they drift and have infinite variance over time. This leads to 'Spurious Regression' (finding patterns where none exist). We must transform data into stationary series (like returns) where the mean and variance are stable, allowing for valid statistical inference.\n\nExample: If you regress the price of Bitcoin against the height of a growing tree, you might find a high correlation ($R^2 > 0.9$) because both are just 'going up'. This is a spurious result. Regressing their daily growth rates (stationary returns) would show zero correlation.",
                    "Cointegration (The Basis of Stat Arb): While two stocks may drift apart individually, they may be 'cointegrated'—meaning a linear combination of them is stationary. Think of a drunk man walking a dog on a leash; they both wander randomly, but they never stay too far apart. Detecting this 'leash' is how we build Mean Reversion and Pairs Trading strategies.\n\nExample: Coke (KO) and Pepsi (PEP) might drift up and down for months, but the *ratio* of their prices tends to stay within a range. If the ratio stretches too far, you sell the expensive one and buy the cheap one, betting they will 'revert' to the mean.",
                    "Hypothesis Testing & The P-Value Trap: In this lab, we demand statistical significance. A 'good-looking' backtest is meaningless unless you can prove the result isn't due to random chance. You must master T-stats, P-values, and the 'Multiple Testing Problem'—if you test 100 random ideas, 5 will look good by pure luck. We use the Bonferroni correction and other methods to filter out these 'false discoveries'.\n\nExample: A trader finds a strategy that only buys on rainy Tuesdays in New York. The P-value is 0.04 (significant!), but since they tested thousands of random 'weather + day' combinations, this is just a 'False Discovery' caused by p-hacking."
                ]
            }
        ],
        "guide": [
            "1. <b>Master the Histogram:</b> Plot the returns of Bitcoin vs. S&P 500. Observe the 'kurtosis' in Bitcoin—the extreme outliers.",
            "2. <b>Linear Algebra Basics:</b> Understand how matrices represent portfolios (Weights × Returns).",
            "3. <b>Statistical Significance:</b> Learn why a Sharpe Ratio of 1.0 requires at least 3 years of data to be statistically valid."
        ],
        "exercise": "<b>Statistical Arbitrage Setup:</b> Pick two related stocks (e.g., KO and PEP). Use a simple spreadsheet or Python to plot their price ratio over 1 year. Identify 'mean-reverting' periods where the ratio stretched too far.",
        "milestone": "🎯 Pass the 'Statistics for Finance' module and build a spreadsheet that calculates Z-Scores for any price series.",
        "common_mistakes": [
            "Assuming normality everywhere: Using a z-score alert system that assumes normal returns will catastrophically misfire during fat-tail events like crashes or squeezes.",
            "P-hacking without knowing it: Running 30 different correlation tests on the same dataset will inevitably surface a 'significant' result by pure chance.",
            "Regressing non-stationary series: Running OLS on raw prices (not returns) produces spurious $R^2$ values that evaporate in live trading.",
            "Ignoring the Multiple Testing Problem: In finance, statistical significance thresholds must be adjusted (Bonferroni, BHY) when testing many strategies simultaneously."
        ],
        "quiz": [
            {
                "question": "Why do quants use Log-Returns instead of simple percentage returns for time-series modeling?",
                "options": ["They are more accurate", "They are time-additive", "They prevent losses", "They are easier to calculate"],
                "answer": 1,
                "explanation": "Log-returns ($ln(P_t/P_{t-1})$) are additive over time, meaning the return of two days is simply the sum of their individual log-returns."
            },
            {
                "question": "If two non-stationary price series have a linear combination that is stationary, they are said to be:",
                "options": ["Correlated", "Vectorized", "Cointegrated", "Normally Distributed"],
                "answer": 2,
                "explanation": "Cointegration is a statistical property where two 'drifting' variables never stay too far apart, forming the basis of pairs trading."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Statistics — Freedman, Pisani & Purves", "url": "https://www.amazon.com/Statistics-4th-David-Freedman/dp/0393929728"},
            {"icon": "🎓", "name": "MIT 18.650: Statistics for Applications", "url": "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/"},
            {"icon": "📖", "name": "Analysis of Financial Time Series — Ruey Tsay", "url": "https://www.amazon.com/Analysis-Financial-Time-Series-Tsay/dp/0470414359"},
            {"icon": "🎓", "name": "Khan Academy: Statistics & Probability", "url": "https://www.khanacademy.org/math/statistics-probability"},
            {"icon": "🌐", "name": "QuantLib: Open Source Quant Library", "url": "https://www.quantlib.org/"}
        ]
    },
    "Stage 3": {
        "title": "Programming & Data",
        "duration": "Months 6–9",
        "difficulty": "Intermediate",
        "reading_time": "35h",
        "prereqs": "Stage 1",
        "goal": "Build a professional-grade research environment using Python.",
        "overview": "A quant is only as good as their data and their ability to manipulate it. This stage transitions you from manual analysis to automated, vectorized research.",
        "topics": [
            {
                "category": "The Computational Quant Stack",
                "items": [
                    {"text": "The Vectorization Paradigm (Pandas vs. Polars): Loops are your enemy. You must master Vectorized operations for high-speed processing. While Pandas is the incumbent, 'Polars' is the modern industry standard for large-scale dataframes due to its multithreaded query engine and lazy evaluation.\n\nExample: Calculating a rolling Z-Score for 100 million ticks might crash Pandas, but Polars can process it in parallel across all CPU cores in a fraction of the time.", "is_interview_prep": True},
                    "Docker for Quant Research: Reproducibility is the hallmark of institutional work. You must learn to containerize your research environment using Docker. This ensures that your backtest runs exactly the same on your local machine, a colleague's laptop, or a cloud server.\n\nExample: You package your Python version, library dependencies (Pandas, Scipy), and API keys into a Docker Image. When you deploy to AWS, you don't have to worry about 'missing library' errors.",
                    "Scientific Visualization: A chart is not just a picture; it is a diagnostic tool. You must go beyond simple line plots to master Interactive Visualization (Plotly, Bokeh). You need to build tools that allow you to overlay trade executions onto the limit order book, visualize volatility surfaces, and detect 'Look-Ahead Bias' visually by seeing if your signals align with future price action.\n\nExample: An interactive Plotly chart allows you to hover over a 'losing' trade and see that it was actually a 'bad print' in the data, not a failure of your strategy's logic."
                ]
            },
            {
                "category": "Data Engineering & Integrity (The 'GIGO' Principle)",
                "items": [
                    "ETL Pipelines & Database Architecture: Garbage In, Garbage Out (GIGO). A professional research lab requires a robust ETL (Extract, Transform, Load) pipeline. You must learn to pull data from APIs (Polygon, Alpaca) or flat files (Parquet, HDF5) and store them in a local SQL or NoSQL database. This ensures data persistence and allows you to run complex queries without re-downloading data every time.\n\nExample: You build a script that runs at 4:05 PM every day, pulls the closing prices for the Russell 3000, checks for missing values, and appends them to your local PostgreSQL database for tonight's research.",
                    "Survivorship Bias & Point-in-Time Data: This is where 90% of retail backtests fail. If you only test on stocks that are in the S&P 500 *today*, you are ignoring all the companies that went bankrupt or were delisted (Survivorship Bias). You must learn to build 'Point-in-Time' datasets that represent the market exactly as it looked on any specific day in the past.\n\nExample: A strategy that buys 'low price-to-book' stocks looks amazing in 2007 if you ignore the dozens of banks that went to zero in 2008. Your backtest must include those bankrupt companies to be realistic.",
                    "The Art of Data Cleaning: Financial data is messy. You will encounter 'bad prints' (erroneous price ticks), missing bars, and corporate actions (Splits, Dividends). You must write robust cleaning algorithms that 'adjust' prices so that a 2-for-1 stock split doesn't look like a 50% crash in your backtest.\n\nExample: Tesla (TSLA) has had several stock splits. Without 'Adjusted Close' data, your backtest would think the stock lost 60-80% of its value in a single day, triggering a false 'stop loss' in your model."
                ]
            }
        ],
        "guide": [
            "1. <b>Set up VS Code:</b> Move away from Jupyter for production code. Use a professional IDE with Git integration.",
            "2. <b>Build a Data Loader:</b> Write a script that downloads 5 years of daily data for the NASDAQ 100 and saves it to a Parquet file.",
            "3. <b>Learn Git:</b> Commit your code daily. Use branches for new strategy ideas."
        ],
        "exercise": "<b>The Vectorized Backtester:</b> Build a 10-line Python script using Pandas that calculates the performance of a 'Moving Average Crossover' strategy. No 'if' statements—use only vectorized logic.",
        "milestone": "🎯 Successfully build a local database that auto-updates every night with closing prices for 500 tickers.",
        "common_mistakes": [
            "Living in Jupyter Notebooks forever: Notebooks are great for exploration but terrible for production. Structure your code as `.py` modules with tests from day one.",
            "Ignoring corporate actions: Failing to adjust prices for splits and dividends will cause your backtest to 'see' fake crashes and phantom rallies.",
            "Downloading data on every run: Not persisting data locally causes slow research loops and breaks reproducibility if a data vendor changes their API.",
            "Using `.iterrows()` in Pandas: This is a loop in disguise and 100–1000x slower than vectorized operations. If you write `.iterrows()`, stop and rethink."
        ],
        "quiz": [
            {
                "question": "What is the primary performance benefit of Vectorization in NumPy/Pandas?",
                "options": ["Easier code", "Avoids memory leaks", "Replaces slow Python loops with C", "Prevents Overfitting"],
                "answer": 2,
                "explanation": "Vectorization performs operations on entire arrays at once using optimized C/C++ backends, bypassing Python's slow global interpreter lock (GIL) and loops."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Python for Finance — Yves Hilpisch", "url": "https://www.amazon.com/Python-Finance-Mastering-Data-Driven/dp/1492024333"},
            {"icon": "💻", "name": "QuantConnect Bootcamps (Free)", "url": "https://www.quantconnect.com/learning"},
            {"icon": "📖", "name": "Python for Data Analysis — Wes McKinney", "url": "https://www.amazon.com/Python-Data-Analysis-Wes-McKinney/dp/109810403X"},
            {"icon": "🌐", "name": "Pandas Official Documentation", "url": "https://pandas.pydata.org/docs/"},
            {"icon": "🌐", "name": "Alpaca Markets: Free Market Data API", "url": "https://alpaca.markets/data"}
        ]
    },
    "Stage 4": {
        "title": "Strategy Building",
        "duration": "Months 9–13",
        "difficulty": "Advanced",
        "reading_time": "50h",
        "prereqs": "Stage 2, 3",
        "goal": "Research and validate your first institutional-grade trading strategies.",
        "overview": "This is where the magic happens. You will combine market intuition, math, and code to find 'Alpha'—market inefficiencies that you can exploit for profit.",
        "topics": [
            {
                "category": "The Alpha Thesis (The 'Why' of a Strategy)",
                "items": [
                    {"text": "Mean Reversion vs. Trend Following: These are the two fundamental strategy 'families'. Trend-followers (CTAs) bet that price moves will persist, while Mean-Reversionists bet that price extremes will return to a long-term average. You must identify which regime the market is in to choose the right strategy.\n\nExample: A Trend strategy buys a stock at a new 52-week high; a Mean Reversion strategy sells it, betting the move is 'overextended'.", "is_interview_prep": True},
                    {"text": "Event-Driven Alpha (Earnings & M&A): Markets often react predictably to specific events. You must learn to model 'Earnings Drift' (PEAD), Index Rebalancing (front-running ETFs), and M&A Arbitrage (betting on deal completion). These are structural sources of alpha that rely on corporate events rather than pure price action.\n\nExample: When a company is added to the S&P 500, massive passive ETFs are *forced* to buy it. Quants front-run this demand by buying the stock as soon as the announcement is made.", "is_interview_prep": True},
                    {"text": "Factor Models & Risk Premia: We move beyond single-indicator signals to Multi-Factor Models. You must understand the 'Fama-French' factors (Size, Value, Momentum) and learn to decompose your returns. Are you actually generating 'Alpha,' or are you just taking on hidden 'Beta' risk (like exposure to small-cap stocks)?\n\nExample: A strategy that buys 'High Dividend' stocks might just be a 'Value' factor in disguise. If 'Value' stocks drop across the board, your strategy will fail, proving it wasn't 'Pure Alpha'.", "is_interview_prep": True},
                    "Alternative Data & Signal Combination: Modern alpha is found in unconventional places: satellite imagery, credit card flows, and Sentiment Analysis of news/social media. You must learn to 'clean' these signals and combine them using techniques like Grinold's Fundamental Law of Active Management ($ IR = IC \\times \\sqrt{Breadth} $).\n\nExample: A hedge fund uses satellite images of Walmart parking lots to predict quarterly sales before they are reported. If the parking lots are fuller than last year, they buy the stock."
                ]
            },
            {
                "category": "The Backtesting Protocol (Scientific Validation)",
                "items": [
                    "Modeling Transaction Costs & Market Impact: A 1% annual edge is easily erased by commissions and slippage. You must learn to build high-fidelity cost models that account for the Bid-Ask Spread and 'Market Impact'—the way your own trades push the price against you.\n\nExample: A high-frequency strategy that makes $0.01 per share might look profitable in a backtest, but once you subtract the $0.005 exchange fee and $0.01 average slippage, the strategy is actually losing money.",
                    "Overfitting & The Multiple Testing Bias: If you torture the data long enough, it will confess to anything. You must learn to detect P-Hacking and avoid the 'Backtest Overfitting' trap. We use techniques like Walk-Forward Analysis and Monte Carlo Simulations to verify that a strategy's performance is robust across different market regimes.\n\nExample: You test 10,000 different combinations of RSI and Moving Averages. You find one that worked perfectly in 2021. This is likely 'overfitting'—the model memorized 2021's specific noise and will fail in 2022.",
                    "Performance Metrics & Risk-Adjusted Returns: We don't just care about the 'P&L'. You must master the Sharpe Ratio, Sortino Ratio (focusing on downside risk), and Maximum Drawdown. A strategy that makes 20% but drops 40% along the way is 'uninvestable' for most institutional capital.\n\nExample: Strategy A returns 15% with a 5% drawdown. Strategy B returns 25% with a 30% drawdown. Most professionals prefer Strategy A because its 'Risk-Adjusted Return' (Sharpe Ratio) is much higher."
                ]
            }
        ],
        "guide": [
            "1. <b>Pick a Niche:</b> Don't try to trade everything. Choose one asset (e.g., FX) and one style (e.g., Trend).",
            "2. <b>Write a Strategy Thesis:</b> Before coding, write 1 paragraph explaining *why* this strategy should make money (e.g., 'It exploits the slow reaction of retail to news').",
            "3. <b>Analyze Drawdowns:</b> Look at the 'worst-case' periods. Could you have survived them mentally?"
        ],
        "exercise": "<b>The Alpha Hunt:</b> Research 'The Turn of the Month Effect' or 'The Monday Effect'. Use your Python tools to see if these seasonalities still exist in the S&P 500 today.",
        "milestone": "🎯 Create a 10-page 'Strategy Tear Sheet' including Sharpe, Max Drawdown, Win Rate, and Return Distribution.",
        "common_mistakes": [
            "Having no economic thesis: 'This pattern worked in the backtest' is not a thesis. If you cannot explain *why* an edge exists, it almost certainly won't survive live trading.",
            "Optimizing parameters on the full dataset: Fitting your RSI period or lookback window on all available data and then calling it a 'backtest' is just curve-fitting with extra steps.",
            "Ignoring drawdown duration: A 15% drawdown that lasts 3 years is psychologically far harder to survive than a 25% drawdown that recovers in 3 months.",
            "Treating Sharpe Ratio as infallible: A Sharpe of 2.0 calculated on 6 months of data is statistically meaningless. You need at least 3 years of out-of-sample returns for a reliable signal."
        ],
        "quiz": [
            {
                "question": "A strategy that returns 20% but experiences a 40% drawdown is often considered 'uninvestable'. Which metric best captures this relationship?",
                "options": ["Log-Return", "Sharpe Ratio", "Information Ratio", "Skewness"],
                "answer": 1,
                "explanation": "The Sharpe Ratio measures excess return per unit of volatility, helping quants determine if the returns justify the risk/drawdown."
            },
            {
                "question": "Which bias occurs if you test a strategy only on stocks currently in the S&P 500, ignoring those that went bankrupt?",
                "options": ["Look-ahead Bias", "Overfitting", "Survivorship Bias", "Small Sample Bias"],
                "answer": 2,
                "explanation": "Survivorship bias creates an upward tilt in results by only including the 'winners' that survived until today."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Algorithmic Trading — Ernest Chan", "url": "https://www.amazon.com/Algorithmic-Trading-Winning-Strategies-Rationale/dp/1118460146"},
            {"icon": "📖", "name": "Expected Returns — Antti Ilmanen", "url": "https://www.amazon.com/Expected-Returns-Investors-Harvesting-Rewards/dp/1119990726"},
            {"icon": "🎓", "name": "WorldQuant University: Free MSc Modules", "url": "https://www.wqu.edu/"},
            {"icon": "🌐", "name": "SSRN: Factor Investing Research Papers", "url": "https://www.ssrn.com/index.cfm/en/"},
            {"icon": "💻", "name": "Backtrader: Python Backtesting Framework", "url": "https://www.backtrader.com/"}
        ]
    },
    "Stage 5": {
        "title": "Advanced Quantitative Methods",
        "duration": "Months 13–19",
        "difficulty": "Expert",
        "reading_time": "60h",
        "prereqs": "Stage 2, 3, 4",
        "goal": "Master the machine learning and portfolio optimization techniques of top hedge funds.",
        "overview": "At this level, you move beyond simple rules to 'dynamic' models. You will learn how to use ML not for price prediction, but for risk management and signal combination.",
        "topics": [
            {
                "category": "Financial Machine Learning (Beyond Prediction)",
                "items": [
                    {"text": "Transformers & Attention Models for Finance: LSTM and RNNs are dated. Modern quants use Transformer-based architectures (like FinBERT) to process sequences of price action and text. You must understand the 'Attention' mechanism and how it can identify long-range dependencies in financial time series.\n\nExample: An attention-based model can recognize that a volatility spike 20 days ago is more relevant to today's risk than a minor price move yesterday.", "is_interview_prep": True},
                    {"text": "Reinforcement Learning (RL) for Execution: Trading is a sequential decision process. You must learn how RL agents (like PPO or DQN) are used to learn 'Optimal Execution'—deciding when and how to place orders to minimize market impact while staying within a risk budget.\n\nExample: An RL agent learns that in a high-volatility market, it should split an order into smaller chunks to avoid 'moving the market' against its own trade.", "is_interview_prep": True},
                    {"text": "The Triple Barrier Method & Meta-Labeling: Traditional ML classification (Buy/Sell) is insufficient for finance. You must master Marcos López de Prado's techniques: the 'Triple Barrier' for labeling events and 'Meta-Labeling' to filter out false signals. This allows your model to decide *whether* to take a trade, rather than just predicting direction, significantly improving the 'Precision' of your signals.\n\nExample: Your primary model predicts 'Buy' for a stock. A secondary 'Meta-Model' (trained only on the success/failure of the first) says 'Ignore this signal' because the current volatility is too high. You avoid a losing trade.", "is_interview_prep": True},
                    "Feature Engineering & Feature Importance: A model is only as good as its inputs. You must learn to engineer 'stationary' features from raw order flow, volatility surfaces, and microstructural imbalances. Crucially, you must use MDA (Mean Decrease Accuracy) or SHAP values to understand *which* features are driving your model and ensure they aren't just memorizing 'noise' from the training set.\n\nExample: You feed a model 'raw price'. It learns that whenever price is $150, it should buy. This is useless. If you feed it 'Z-Score of Volume,' it learns that abnormal volume precedes a move, which is a generalized feature.",
                    "Purging & Embargoing (Time Series CV): Standard Cross-Validation fails in finance because of 'Information Leakage' (future data influencing the past via overlapping time series). You must learn to implement Purged K-Fold Cross-Validation, which removes data points between training and testing sets to ensure the model is truly generalizing to unseen environments.\n\nExample: If your trade label spans 5 days, and you use day 3 in your training set and day 4 in your test set, the model already 'knows' the outcome of the trade. Purging removes those overlapping days to prevent cheating."
                ]
            },
            {
                "category": "Modern Portfolio Construction",
                "items": [
                    "From Mean-Variance to Hierarchical Risk Parity (HRP): Traditional Markowitz optimization is 'unstable'—small changes in inputs lead to massive changes in allocations. You must study Hierarchical Risk Parity (HRP), which uses graph theory and machine learning to cluster assets based on correlation and allocate risk more robustly, avoiding the 'concentration risk' of older models.\n\nExample: In 2022, both Stocks and Bonds dropped together. A traditional 60/40 portfolio failed. An HRP portfolio might have identified the rising correlation early and shifted weight into commodities or cash to maintain its risk target.",
                    "Factor Neutralization & Hedging: A professional quant doesn't just want to make money; they want to make 'uncorrelated' money. You must learn to Factor Neutralize your portfolio—hedging out unwanted exposures to Market, Sector, or Interest Rate risks so that only your 'Pure Alpha' remains. This is how you achieve the 'Holy Grail' of finance: a Sharpe Ratio > 2.0.\n\nExample: You have a strategy that buys Tech stocks. To ensure you aren't just 'Long Tech,' you sell an equal dollar amount of a Tech ETF (QQQ). Now, you only profit if your specific stocks outperform the rest of the Tech sector.",
                    "The Black-Litterman Model: This is the bridge between market equilibrium and your subjective research views. You must learn to use Bayesian Inference to combine the 'Market Cap Weighted' portfolio with your specific alpha signals, allowing for a more stable and theoretically sound allocation than raw optimization.\n\nExample: The market says Apple should be 7% of your portfolio. Your AI model says Apple is overvalued. Black-Litterman allows you to tilt your weight to 5% without completely ignoring the market's collective wisdom."
                ]
            }
        ],
        "guide": [
            "1. <b>Learn Scikit-Learn:</b> Master Random Forests and Gradient Boosting for classification tasks.",
            "2. <b>Study Volatility:</b> Understand 'GARCH' models to forecast when markets will become dangerous.",
            "3. <b>Factor Neutralization:</b> Learn how to hedge out 'Market Risk' so you only profit from your specific alpha."
        ],
        "exercise": "<b>The Regime Detector:</b> Build a K-Means clustering model in Python that categorizes the market into 3 states: 'Low Vol/Bull', 'High Vol/Bear', and 'Sideways/Chop'.",
        "milestone": "🎯 Implement a machine learning model that achieves a 'Precision' of >55% on out-of-sample directional signals.",
        "common_mistakes": [
            "Using standard K-Fold CV on time series: Shuffling time-series data before splitting leaks future information into the training set, making results completely unreliable.",
            "Feeding raw price as an ML feature: Price levels are non-stationary and provide no generalizable signal. Always engineer stationary, normalized features (returns, z-scores, ratios).",
            "Maximizing Accuracy instead of Precision: In imbalanced financial datasets, 90% accuracy means nothing if you are predicting 'hold' for every bar. Focus on Precision and Recall of your signal.",
            "Ignoring feature correlation: Highly correlated features don't add information — they add noise and can destabilize tree-based models. Use SHAP/MDA to prune redundant inputs."
        ],
        "quiz": [
            {
                "question": "What is the purpose of 'Meta-Labeling' in a financial machine learning pipeline?",
                "options": ["To predict price", "To filter false positive signals from a primary model", "To replace OLS regression", "To speed up training"],
                "answer": 1,
                "explanation": "Meta-labeling (López de Prado) uses a secondary model to decide *whether* to take a trade suggested by a primary model, improving overall signal precision."
            },
            {
                "question": "Why is 'Purged Cross-Validation' necessary for time-series data?",
                "options": ["To remove bad data", "To prevent information leakage between training and testing folds", "To handle missing values", "To reduce volatility"],
                "answer": 1,
                "explanation": "In time series, data points are often serially correlated. Purging ensures that training data doesn't contain information about the 'future' in the validation set."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Advances in Financial Machine Learning — López de Prado", "url": "https://www.amazon.com/Advances-Financial-Machine-Learning-Marcos/dp/1119482089"},
            {"icon": "📖", "name": "Options, Futures & Other Derivatives — John Hull", "url": "https://www.amazon.com/Options-Futures-Other-Derivatives-10th/dp/013447208X"},
            {"icon": "🌐", "name": "mlfinlab: Financial ML Python Library", "url": "https://github.com/hudson-and-thames/mlfinlab"},
            {"icon": "🎓", "name": "Coursera: Machine Learning Specialization", "url": "https://www.coursera.org/specializations/machine-learning-introduction"},
            {"icon": "🌐", "name": "PyPortfolioOpt: Portfolio Optimization", "url": "https://pyportfolioopt.readthedocs.io/en/latest/"}
        ]
    },
    "Stage 6": {
        "title": "Professional Mastery",
        "duration": "Month 19+",
        "difficulty": "Expert",
        "reading_time": "40h",
        "prereqs": "Stage 4, 5",
        "goal": "Operate as a full-stack Quant Researcher capable of running institutional capital.",
        "overview": "The final stage is about infrastructure, scale, and longevity. You transition from a 'researcher' to a 'portfolio manager' who manages risk as much as they seek returns.",
        "topics": [
            {
                "category": "Institutional Execution (The 'Plumbing' of Alpha)",
                "items": [
                    {"text": "Prime Brokerage & Margin Mechanics: Professional quants don't trade on retail accounts. You must understand 'Prime Brokerage'—the specialized lenders that provide leverage, stock borrow for shorting, and clearing services. You will study 'Haircuts' and 'Portfolio Margin' to understand how much capital you actually have to deploy.\n\nExample: In a retail account, your leverage is 2:1. In a prime-brokerage account using 'Portfolio Margin,' you might achieve 6:1 leverage if your portfolio is well-hedged.", "is_interview_prep": True},
                    {"text": "Regulatory & Compliance Basics: Finance is highly regulated. You must learn about Reg NMS (Best Execution), MiFID II (Transparency), and 'Wash Sale' rules. A strategy that looks profitable but violates compliance rules is a liability, not an asset.\n\nExample: You build a strategy that 'washes' trades (buying and selling to yourself) to create fake volume. This is illegal 'Market Manipulation' and can lead to prison time, regardless of the P&L.", "is_interview_prep": True},
                    "Algorithmic Execution & Market Impact: Once you have a signal, you must execute it without 'alerting' the rest of the market. You must learn the mechanics of VWAP (Volume Weighted Average Price), TWAP (Time Weighted Average Price), and IS (Implementation Shortfall). You will build algorithms that 'slice' large orders into thousands of micro-orders to hide your intention from predatory HFT (High-Frequency Trading) bots.\n\nExample: You need to buy 1 million shares of MSFT. Instead of one large order, you use a VWAP algorithm that buys 100 shares every minute throughout the day, matching the historical volume profile to avoid pushing the price up."
                ]
            },
            {
                "category": "The Professional Practice of Quant Finance",
                "items": [
                    "Tail Risk & Black Swan Management: A 'good' strategy can be killed by a single 'unprecedented' event. You must learn to model Tail Risk and implement hedging strategies (like buying deep out-of-the-money puts) to protect your fund from 'Black Swan' events. We manage for the 1% scenario just as much as the 99% scenario.\n\nExample: During the 2020 COVID crash, most portfolios dropped 30%. A fund with a 'Tail Risk' hedge might have had Put Options that surged 1,000% in value, offsetting the losses in their stock positions.",
                    "Capacity Analysis & Alpha Decay: Alpha is a finite resource. As you manage more capital, your own trading begins to eat your profits. You must learn to perform Capacity Analysis—determining the 'AUM' (Assets Under Management) limit of your strategy before it becomes too large to execute. You must also monitor for Alpha Decay, recognizing when a market inefficiency has been 'arbitraged away' by competitors.\n\nExample: A strategy that trades 'Micro-cap' stocks might have a capacity of only $10 million. If you try to trade $1 billion, your own buying will push the price up so much that the profit disappears.",
                    "The Ethics & Integrity of Research: A professional quant is a scientist first. You must maintain a Research Journal with academic rigor, documenting every failed experiment and preventing 'Result Mining'. You have a fiduciary duty to your investors and a systemic duty to the market to operate with transparency, ethics, and intellectual honesty.\n\nExample: Instead of just showing your boss the 'best' backtest, you show them all 50 failed versions and explain why the 51st one is theoretically sound and not just a lucky fluke."
                ]
            }
        ],
        "guide": [
            "1. <b>Build a Production Pipeline:</b> Use Docker and AWS/GCP to run your research scripts on a schedule.",
            "2. <b>Network:</b> Start contributing to open-source quant libraries or publishing research on SSRN/arXiv.",
            "3. <b>Capital Allocation:</b> Learn the business of quant: how to pitch a strategy to a PM or Seed Fund."
        ],
        "exercise": "<b>The 'Flash Crash' Test:</b> Simulate how your current 'best' strategy would have performed during the 2010 Flash Crash or the 2020 COVID crash. Did it blow up?",
        "milestone": "🎯 Deploy a live 'Paper Trading' portfolio of 3+ diversified strategies and maintain a Sharpe > 1.5 for 6 months.",
        "common_mistakes": [
            "Underestimating market impact at scale: A strategy with 20% annual returns may have a capacity of only $5M. Beyond that, your own orders move the market against you.",
            "Treating paper trading as validation: Paper trading does not simulate slippage, partial fills, or the emotional weight of real capital at risk. Use it for mechanics, not for performance proof.",
            "Not monitoring for alpha decay: An edge that existed in 2018 may be fully arbitraged away by 2025. You must continuously monitor live performance vs. the historical backtest benchmark.",
            "Skipping the research journal: Not documenting failed experiments means you will re-invent them. A research log is not optional — it is institutional best practice."
        ],
        "quiz": [
            {
                "question": "What does a VWAP (Volume Weighted Average Price) execution algorithm aim to achieve?",
                "options": ["The highest possible profit", "Execution that matches the day's volume profile to minimize market impact", "Instant order filling", "Arbitrage between exchanges"],
                "answer": 1,
                "explanation": "VWAP algorithms slice large orders into smaller ones throughout the day to hide institutional footprints and minimize price distortion."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Active Portfolio Management — Grinold & Kahn", "url": "https://www.amazon.com/Active-Portfolio-Management-Quantitative-Approach/dp/0070248826"},
            {"icon": "📖", "name": "The Man Who Solved the Market — Zuckerman", "url": "https://www.amazon.com/Man-Who-Solved-Market-Renaissance/dp/073521798X"},
            {"icon": "🌐", "name": "Interactive Brokers API Documentation", "url": "https://interactivebrokers.github.io/tws-api/"},
            {"icon": "🌐", "name": "arXiv Quantitative Finance Papers", "url": "https://arxiv.org/list/q-fin/recent"},
            {"icon": "🎓", "name": "AWS: Cloud for Quant Finance", "url": "https://aws.amazon.com/financial-services/capital-markets/"}
        ]
    },
    "Stage 7": {
        "title": "Macroeconomics for Financial Markets & Trading",
        "duration": "Advanced Elective",
        "difficulty": "Intermediate",
        "reading_time": "30h",
        "prereqs": "Stage 1",
        "goal": "Master how macroeconomic forces drive asset prices across global markets using institutional frameworks.",
        "overview": "A comprehensive course designed to teach you how macroeconomic forces drive asset prices across global markets. Built from the same frameworks used by institutional traders, this stage bridges the gap between pure quantitative modeling and global macro reality.",
        "topics": [
            {
                "category": "Monetary Policy & Rates (The Global Cost of Capital)",
                "items": [
                    "Central Bank Policy Mechanics: You must understand the 'plumbing' of the Fed, ECB, and BoJ. This involves analyzing the Federal Funds Rate, the 'Dot Plot' for rate expectations, and the impact of Quantitative Easing/Tightening on market liquidity. We don't just follow the news; we model the OIS (Overnight Indexed Swap) spreads to see where the market thinks rates are going. \n*Example:* In early 2022, while the Fed was still officially 'dovish,' the Eurodollar futures market was already pricing in 7+ rate hikes, providing a leading signal for the massive sell-off in growth equities.",
                    "Rate Expectations & Forward Guidance: Learn to decode 'Central Bank Speak.' You must distinguish between 'hawkish' and 'dovish' shifts and quantify their impact on the discount rates used in valuation models. Understanding 'Neutral Rates' (R-star) is critical for determining if policy is restrictive or stimulative. \n*Example:* A subtle change in FOMC minutes from 'patient' to 'data-dependent' can trigger a multi-standard deviation move in the USD as traders front-run the end of an easing cycle."
                ]
            },
            {
                "category": "Yield Curve Analysis & Fixed Income (The Market's Crystal Ball)",
                "items": [
                    "The Term Structure of Interest Rates: The yield curve is the most powerful leading indicator in finance. You must master the dynamics of 'Bull Flattening,' 'Bear Steepening,' and 'Inversions.' You will learn to use the 2s10s and 3m10y spreads to forecast economic recessions and regime shifts. \n*Example:* An inverted yield curve (short-term rates higher than long-term) has preceded every US recession for decades. As a quant, you model the 'risk premium' embedded in the long end of the curve.",
                    "Real vs. Nominal Yields: Inflation is the enemy of fixed income. You must understand the relationship between Nominal Yields, Inflation Break-evens, and Real Yields (TIPS). Real yields are the true 'gravity' for high-multiplier tech stocks—when real yields rise, growth valuations compress. \n*Example:* In 2022, Real Yields moved from -1% to +1.5%. This shift was the primary driver behind the 'valuation reset' in the NASDAQ, regardless of individual company earnings."
                ]
            },
            {
                "category": "Global Macro Frameworks (The Drivers of Flow)",
                "items": [
                    {"text": "The Global Liquidity Cycle: Markets are driven by the expansion and contraction of central bank balance sheets (M2 liquidity). You must learn to track 'G4 Central Bank Liquidity' to understand the primary tailwind or headwind for all risk assets.\n\nExample: When the Fed initiates 'Quantitative Easing' (QE), liquidity enters the system, suppressing volatility and pushing asset prices higher, regardless of fundamentals.", "is_interview_prep": True},
                    {"text": "China Macro & EM Flows: China's credit cycle is a major driver of global commodities and industrial metals. You must study the 'China Credit Impulse' and how PBOC policy shifts impact Emerging Markets (EM) and the USD/CNY exchange rate.\n\nExample: A contraction in Chinese credit often precedes a drop in Copper prices and Australian Dollar (AUD) weakness, as Australia is a primary commodity exporter to China.", "is_interview_prep": True},
                    "Risk-On vs. Risk-Off Regimes: Macro trading is about identifying the 'dominant theme'—is it Inflation, Growth, or Liquidity? You will learn to identify 'regime shifts' using cross-asset signals, such as the AUD/JPY pair (proxy for global risk appetite) or the Copper/Gold ratio (proxy for global growth).\n\nExample: A breakdown in the Copper/Gold ratio often precedes a stock market correction, as it signals that industrial demand is falling while safety-seeking demand is rising."
                ]
            },
            {
                "category": "Economic Data Interpretation (Signal vs. Noise)",
                "items": [
                    "The Holy Trinity of Data: Inflation (CPI/PCE), Employment (NFP), and Growth (GDP/ISM). You must go beyond the 'headline' number to analyze the 'internals.' Is inflation driven by sticky services or volatile energy? Is employment growth driven by full-time jobs or part-time noise? \n*Example:* A 'beat' on the NFP headline might look bullish, but if the 'Average Hourly Earnings' are cooling, the Fed might stay on hold, making the report actually bullish for Bonds and neutral for Equities.",
                    "Leading vs. Lagging Indicators: Most economic data is 'rear-view mirror.' You must learn to prioritize Leading Indicators (ISM New Orders, Building Permits, Consumer Sentiment) over Lagging ones (Unemployment Rate, GDP) to position your portfolio before the crowd. \n*Example:* The ISM Manufacturing 'New Orders' component often peaks 6-9 months before a recession begins, giving quants a massive head start on de-risking portfolios."
                ]
            },
            {
                "category": "Applied Macro Trading Strategies",
                "items": [
                    "Thematic Macro Overlays: Learn to translate macro views into 'expressive' trades. This includes 'Inflation Hedges' (Long Commodities, Short Duration), 'Growth Transitions' (Cyclicals vs. Defensives), and 'Policy Divergence' trades (Long USD / Short JPY). \n*Example:* If the Fed is hiking while the BoJ is keeping rates at zero, the 'Interest Rate Differential' creates a massive tailwind for the USD/JPY 'Carry Trade.'",
                    "Macro-Quant Integration: The ultimate goal is 'Systematic Macro'—using quantitative rules to trade macro themes. You will learn to build 'Trend Following' models on macro-sensitive assets and 'Carry' models that exploit interest rate differentials across global currencies. \n*Example:* A systematic macro fund might use a 'Signal Combo' of Momentum (price action) + Macro (rate differentials) to achieve higher risk-adjusted returns than a simple trend-follower."
                ]
            }
        ],
        "guide": [
            "1. <b>Follow the Fed:</b> Read the FOMC statements and listen to the Chair's press conference. Note the market reaction in the 2-Year Yield.",
            "2. <b>Build a Macro Dashboard:</b> Track the DXY, 10Y Yield, Brent Oil, and S&P 500 on one screen to see the correlations.",
            "3. <b>Study Economic Releases:</b> Use an economic calendar to track NFP and CPI releases. Observe how the 'surprise' (actual vs forecast) drives volatility."
        ],
        "exercise": "<b>The Yield Curve Playbook:</b> Plot the 2s10s spread over the last 20 years. Highlight the periods where it inverted and measure the time between inversion and the subsequent stock market peak.",
        "milestone": "🎯 Build a 'Macro Regime Monitor' that classifies the current environment into one of four quadrants: Goldilocks, Reflation, Stagflation, or Deflation.",
        "common_mistakes": [
            "Trading the headline number, not the internals: A 'beat' on headline CPI can be bearish for equities if core services inflation is re-accelerating — always decompose the data.",
            "Confusing correlation with causation in cross-asset: The Copper/Gold ratio signals growth expectations — it does not *cause* them. Don't build a trading rule on a ratio without understanding the underlying mechanism.",
            "Ignoring central bank credibility: Policy models assume central banks act rationally and predictably. Political interference or credibility crises (e.g., Turkey, Argentina) can invalidate standard macro frameworks entirely.",
            "Being too early on macro trades: A yield curve inversion can persist for 12–24 months before a recession materializes. Sizing correctly for a long-dated macro trade is as important as being directionally correct."
        ],
        "quiz": [
            {
                "question": "Which yield curve regime is historically most associated with an impending recession?",
                "options": ["Bull Steepening", "Bear Flattening", "Inversion (Short rates > Long rates)", "Parallel Shift Up"],
                "answer": 2,
                "explanation": "Yield curve inversion has preceded almost every major US recession, signaling that the market expects lower future growth and inflation."
            },
            {
                "question": "What is the impact of rising 'Real Yields' on growth-oriented technology stocks?",
                "options": ["Prices rise due to liquidity", "Valuations compress as the discount rate increases", "No correlation", "Dividends increase"],
                "answer": 1,
                "explanation": "Real yields act as 'gravity' for valuations. As the risk-free real return rises, the present value of future earnings (high in growth stocks) drops."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Macroeconomics — Gregory Mankiw", "url": "https://www.amazon.com/Macroeconomics-N-Gregory-Mankiw/dp/1319105998"},
            {"icon": "🎓", "name": "Real Vision: Institutional Macro Insights", "url": "https://www.realvision.com/"},
            {"icon": "🎓", "name": "MacroVoices Podcast", "url": "https://www.macrovoices.com/"},
            {"icon": "📖", "name": "The Alchemy of Finance — George Soros", "url": "https://www.amazon.com/Alchemy-Finance-George-Soros/dp/0471445494"},
            {"icon": "🌐", "name": "FRED Economic Data (St. Louis Fed)", "url": "https://fred.stlouisfed.org/"}
        ]
    },
    "Stage 8": {
        "title": "Options & Derivatives Pricing",
        "duration": "Advanced Elective",
        "difficulty": "Advanced",
        "reading_time": "40h",
        "prereqs": "Stage 2",
        "goal": "Master the mathematics and market intuition behind derivatives pricing, the Greeks, volatility surfaces, and options-based trading strategies.",
        "overview": "Options are the most powerful instrument in a quant's toolkit — and the most dangerous if misunderstood. This stage moves beyond directional bets into volatility trading, non-linear payoffs, and the institutional use of derivatives for hedging, income generation, and pure alpha. You will learn why the 'price' of an option is really the 'price of uncertainty.'",
        "topics": [
            {
                "category": "The Black-Scholes Framework & Its Limits",
                "items": [
                    "Black-Scholes-Merton (BSM) Model: The Nobel Prize-winning foundation of options pricing. You must understand its derivation intuitively: an option's fair value is determined by five inputs — Spot Price, Strike Price, Time to Expiry, Risk-Free Rate, and *Implied Volatility*. The model assumes continuous trading, no dividends, and log-normally distributed returns — all assumptions that break down in the real world.\n\nExample: BSM would price a 1-month at-the-money SPY put at roughly $5.00. In reality, after a geopolitical shock, the *market* might price it at $7.50 due to higher implied volatility, even if the mathematical 'fair value' hasn't changed.",
                    "The Volatility Smile & Skew (BSM's Fatal Flaw): Under BSM, implied volatility should be *constant* across strikes. In reality, out-of-the-money puts trade at a *higher* implied volatility than at-the-money options (the 'Skew'). This is the market pricing in the risk of a crash — a feature BSM ignores entirely. Mastering the 'Skew' is the gateway to institutional-grade vol trading.\n\nExample: After the 1987 Black Monday crash, the options market never forgot. Since then, SPX put options at a 10% out-of-the-money strike consistently trade at 4–6 vol points *above* the at-the-money implied vol — the market's permanent 'crash insurance' premium.",
                    "Jump-Diffusion & Stochastic Volatility Models: Because BSM fails for fat tails, quants use more advanced models: Heston (volatility is itself stochastic), SABR (widely used in fixed income), and VG/NIG (variance-gamma models that incorporate jumps). You must understand the conceptual difference between models that assume continuous price paths vs. those that allow for instantaneous 'jumps'.\n\nExample: During a biotech earnings release, a stock can gap 40% overnight — a 'jump' that a continuous diffusion model assigns zero probability to. A jump-diffusion model like Merton's would correctly price the elevated cost of short-dated options around the event."
                ]
            },
            {
                "category": "The Greeks (Sensitivities & Risk Management)",
                "items": [
                    {"text": "Delta & Delta Hedging: Delta (Δ) measures how much an option's price changes for a $1 move in the underlying. Market makers *delta-hedge* their books constantly — buying or selling the underlying to remain 'Delta-Neutral,' profiting from the bid-ask spread while eliminating directional exposure.\n\nExample: You sell a call option with a Delta of 0.40. To hedge, you buy 40 shares of the stock for every 100-share option contract. If the stock rises $1, your option loss is offset by your stock gain.", "is_interview_prep": True},
                    {"text": "Gamma, Theta & the P&L of a Hedged Book: Gamma (Γ) measures the *rate of change* of Delta. Theta (Θ) measures time decay — the amount an option loses in value per day. The core tension of options market making is Gamma vs. Theta: long options positions have positive Gamma (you benefit from large moves) but negative Theta (you pay for that privilege daily).\n\nExample: You buy a straddle (a call + a put) on NVDA earnings. Every day that NVDA stays flat, you lose Theta. But if NVDA gaps 20%, your Gamma means your Delta skyrockets, generating a large profit that exceeds all the Theta you paid.", "is_interview_prep": True},
                    "Vega & Rho (Volatility & Rate Sensitivity): Vega (ν) measures sensitivity to changes in implied volatility. A long option position is always 'long Vega' — it benefits if the market becomes more fearful (higher IV). Rho measures sensitivity to interest rates — critically important for long-dated options (LEAPS) where the risk-free rate discount is significant.\n\nExample: In early 2022, when the Fed began hiking rates aggressively, long-dated tech call options (LEAPS) suffered not from the underlying price alone, but from their Rho exposure — the higher discount rate compressed their present value."
                ]
            },
            {
                "category": "Volatility as an Asset Class",
                "items": [
                    "Implied vs. Realized Volatility: Implied Volatility (IV) is the market's *forecast* of future volatility embedded in option prices. Realized Volatility (RV) is the *actual* volatility that occurred. The Volatility Risk Premium (VRP) is the persistent tendency for IV to *exceed* RV on average, meaning option sellers are systematically paid for bearing tail risk.\n\nExample: SPX implied volatility (VIX) averages around 19%, but realized volatility historically averages closer to 15%. Systematically selling options and delta-hedging captures this ~4-point 'VRP' — the core of many hedge fund 'vol selling' strategies.",
                    "The Volatility Surface: The 3D surface of implied volatility across all strikes (the 'Skew') and all expiration dates (the 'Term Structure') is the full picture of the options market's expectations. You must learn to 'read' the surface — a steep term structure signals calm short-term but fear longer-term; a flat surface signals uniform uncertainty.\n\nExample: Before a major FOMC meeting, short-dated IV spikes (expensive near-term options) while long-dated IV remains calm. The surface 'kinks' at the event date. Traders 'buy the kink' by buying cheap long-dated options and selling the expensive short-dated ones in a Calendar Spread.",
                    "The VIX & Volatility Term Structure: The VIX Index measures the implied volatility of 30-day SPX options. VIX Futures trade the *expected* VIX in the future. The most reliable volatility trade is exploiting 'Contango' in the VIX futures curve — when future VIX is priced above spot VIX, futures roll down over time, creating a structural shorting opportunity.\n\nExample: The ETF XIV (short VIX) returned over 50% per year for 7 years by mechanically shorting VIX futures in contango — until February 2018, when a single day's volatility spike caused a 96% loss, a reminder that VRP harvesting carries catastrophic tail risk."
                ]
            },
            {
                "category": "Options Strategies & Institutional Applications",
                "items": [
                    "Directional Options Strategies: Buying naked calls or puts is not a quant strategy — it is speculation. You must master *defined-risk* spreads: Bull Call Spreads, Bear Put Spreads, and Risk Reversals that give you directional exposure while capping premium outlay and making your breakeven explicit.\n\nExample: Instead of buying a $500 TSLA call outright, you buy the $500/$550 Call Spread for $15. Your max loss is $15; your max profit is $35. Your Vega exposure is dramatically lower, meaning a vol crush after earnings hurts you far less.",
                    "Income & Hedging Strategies (Institutional Use): Institutions use options for yield enhancement (Covered Calls, Cash-Secured Puts) and portfolio protection (Protective Puts, Collars). A quant's role is to price these strategies systematically and determine when buying insurance is mathematically justified vs. when it destroys returns.\n\nExample: A pension fund holding $1 billion of S&P 500 exposure might buy a 3-month 10% out-of-the-money put for 0.4% of NAV. The quant runs a backtest to determine that this hedge *saves* more than 0.4% in avoided drawdown during crash regimes, making the insurance net-positive EV."
                ]
            }
        ],
        "guide": [
            "1. <b>Start with Options Pricing Calculators:</b> Use an online BSM calculator (CBOE has one free). Input different strikes and expiries and observe how IV changes the price more than any other input.",
            "2. <b>Simulate a Delta Hedge:</b> Using daily SPY data, simulate being short a call option and delta-hedging it daily. Calculate your P&L from Gamma gains vs. Theta paid.",
            "3. <b>Read the VIX Term Structure Daily:</b> Every morning, look at the VIX Futures curve on vixcentral.com. Notice if it is in Contango (normal) or Backwardation (fear). Track what happens to markets under each regime."
        ],
        "exercise": "<b>The Volatility Surface Builder:</b> Use Python and the `yfinance` library to download options chain data for SPY. Extract the implied volatility for each strike and expiry. Plot the 3D surface using Plotly. Identify the Skew — do out-of-the-money puts have higher IV than calls?",
        "milestone": "🎯 Build a delta-hedging simulation that correctly calculates daily P&L (Gamma PnL + Theta decay) for a short straddle position over a 30-day period.",
        "common_mistakes": [
            "Buying options without understanding Theta: Buying weekly options and holding them through time decay is the fastest way to lose money in options. Time is *always* working against the buyer.",
            "Ignoring Implied Volatility Rank (IVR): Buying options when IV is at a 52-week high (expensive) and selling them when IV is at a 52-week low (cheap) is a common and costly error.",
            "Confusing Delta with probability of profit: A 0.30 Delta option does not have a 30% probability of being in-the-money at expiry. The correct measure is N(d2), not N(d1), from the BSM formula.",
            "Selling naked options without tail-risk management: Selling uncovered puts or calls for premium income is seductive until a black swan event delivers a loss that exceeds years of collected premium in a single day."
        ],
        "quiz": [
            {
                "question": "Which 'Greek' measures an option's sensitivity to time decay?",
                "options": ["Delta", "Gamma", "Theta", "Vega"],
                "answer": 2,
                "explanation": "Theta (Θ) represents the daily loss in an option's value as it approaches expiration, assuming no change in the underlying price or volatility."
            },
            {
                "question": "What does a 'Positive Gamma' position mean for an options trader?",
                "options": ["They lose money if the market moves", "Their Delta increases as the underlying moves in their favor", "They are short volatility", "They benefit from time passing"],
                "answer": 1,
                "explanation": "Positive Gamma means your directional exposure (Delta) grows in the direction of the move, allowing you to profit from large 'jumps' in price."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Options, Futures & Other Derivatives — John Hull", "url": "https://www.amazon.com/Options-Futures-Other-Derivatives-10th/dp/013447208X"},
            {"icon": "📖", "name": "The Volatility Surface — Jim Gatheral", "url": "https://www.amazon.com/Volatility-Surface-Practitioners-Guide/dp/0471792519"},
            {"icon": "🎓", "name": "CBOE Options Institute: Free Education", "url": "https://www.cboe.com/education/"},
            {"icon": "🌐", "name": "VIX Central: VIX Term Structure Monitor", "url": "http://vixcentral.com/"},
            {"icon": "🎓", "name": "tastytrade: Practical Options Trading", "url": "https://tastytrade.com/learn/"},
            {"icon": "🌐", "name": "QuantLib: Options Pricing Library", "url": "https://www.quantlib.org/"}
        ]
    },
    "Stage 9": {
        "title": "HFT & Low-Latency Infrastructure",
        "duration": "Months 12–18",
        "difficulty": "Expert",
        "reading_time": "60h",
        "prereqs": "Stage 1, Stage 6",
        "goal": "Master the hardware and software architectures required to compete in the sub-millisecond trading domain.",
        "overview": "The world of HFT is the extreme frontier of quantitative finance. At this level, alpha is measured in microseconds. This stage bridges the gap between pure mathematical finance and high-performance engineering, covering the 'plumbing' that allows institutional firms to harvest liquidity and manage risk at lightning speed.",
        "topics": [
            {
                "category": "The HFT Tech Stack (Hardware & OS)",
                "items": [
                    {"text": "Colocation & The Physics of Latency: In HFT, the speed of light is a constraint. You must understand 'Colocation'—placing servers in the same exchange data center to minimize travel distance. You will study how 'Fiber Optics' vs 'Microwave Towers' transmit data between hubs (e.g., Chicago to New Jersey), and why a 1-microsecond advantage can be worth millions.\n\nExample: HFT firms pay for 'Equalized Cable Lengths' within a data center to ensure no participant has a physical advantage over another. Even a 50-foot difference in cable length can create a 'latency' gap that is exploitable.", "is_interview_prep": True},
                    "Kernel Bypass & Low-Latency Linux: Standard operating systems are too slow. You must learn about 'Kernel Bypass' (e.g., Solarflare OpenOnload) which allows applications to talk directly to the Network Interface Card (NIC), skipping the OS kernel to save microseconds. You will study 'Interrupt Coalescing,' 'CPU Pinning,' and 'L1/L2 Cache Optimization' to ensure your trading logic never leaves the processor.",
                    {"text": "FPGA & Hardware Acceleration: When C++ is too slow, we use hardware. You must understand the role of Field-Programmable Gate Arrays (FPGAs) in HFT—chips that are 'hard-wired' for specific tasks like order parsing and risk checks. FPGAs provide 'Deterministic Latency,' meaning every trade takes exactly the same amount of time, regardless of market volatility.\n\nExample: An FPGA can receive a market tick, run a simple risk check, and generate a 'cancel order' message in under 100 nanoseconds—far faster than any software-based system."}
                ]
            },
            {
                "category": "Network Protocols & Connectivity",
                "items": [
                    "FIX, SBE, & Binary Protocols: Financial Information eXchange (FIX) is the industry standard, but for HFT, it is often too 'chatty' (text-based). You must master 'Binary Protocols' like Simple Binary Encoding (SBE) and ITCH/OUCH, which transmit data in raw bytes to maximize throughput and minimize parsing time.",
                    "Market Data Dissemination: You will study how exchanges 'multicast' data to participants. You must learn about 'Gap Recovery' (how to handle missed packets) and the trade-offs between 'TCP' (reliable but slow) and 'UDP' (fast but unreliable) in a high-traffic environment.",
                    {"text": "Direct Market Access (DMA) & Pre-Trade Risk: Every HFT order must pass through a risk gate. You will study 'Lamped' vs 'Naked' DMA and how to build sub-microsecond pre-trade risk checks that ensure you don't accidentally bankrupt the firm due to a software bug.\n\nExample: A 'Fat Finger' check on an FPGA ensures that no single order can exceed $1M in value. If a bug tries to send a $100M order, the hardware blocks it before it ever hits the network."}
                ]
            },
            {
                "category": "Advanced Microstructure II",
                "items": [
                    {"text": "Adverse Selection & Toxic Flow: In HFT, 'losing' often means being 'picked off' by someone faster. You must model 'Adverse Selection'—the risk that you only get filled when the market is about to move against you. You will study 'VPIN' (Volume-Synchronized Probability of Informed Trading) and how to detect 'Informed Flow'.\n\nExample: If you are bidding $100.00 and a 'faster' participant sees a massive buy order coming in, they will 'taker' your liquidity instantly, and you are left short as the price moves to $100.05.", "is_interview_prep": True},
                    "Order Type Physics: Beyond simple Limit/Market orders, you must master 'Icebergs' (hidden size), 'Post-Only' (ensuring you are a maker), and 'Immediate-or-Cancel' (IOC). You will study 'Queue Position Optimization'—how to stay at the front of the line at a specific price level.",
                    {"text": "The Math of Tick-by-Tick Signal: You will move from 'Bar-based' research to 'Tick-based' research. You must learn to model 'Order Book Imbalance,' 'Trade-Flow Centrality,' and 'Micro-Price' dynamics using High-Frequency Econometrics.\n\nExample: By analyzing the ratio of 'Cancelled' vs 'Executed' orders in the first 5 levels of the book, you can predict the direction of the next 'mid-price' move with 60% accuracy over a 50-millisecond horizon."}
                ]
            }
        ],
        "guide": [
            "1. Learn C++ (Focus on Template Metaprogramming and RAII)",
            "2. Study Network Engineering (TCP/IP stack, Multicast, UDP)",
            "3. Build a simple Order Book Parser in Python, then port it to C++",
            "4. Research 'Market Impact' models using L3 (Message-level) data",
            "5. Apply for internships at HFT firms (Citadel, Optiver, Jane Street, Hudson River Trading)"
        ],
        "exercise": "<b>The Latency Race:</b> Write a C++ program that parses a simulated binary market data feed. Measure the 'Tick-to-Trade' latency using a high-resolution clock. Optimize the code until your parsing time is under 5 microseconds.",
        "milestone": "🎯 Build a 'Micro-Regime Classifier' that detects 'Toxic Order Flow' in real-time using a 50ms rolling imbalance window.",
        "common_mistakes": [
            "Ignoring 'Tick-to-Trade' latency: A 1ms signal is useless in an HFT environment if your execution takes 10ms.",
            "Overfitting on 'Empty' Books: Many strategies look great on historical data but fail in live markets because they assume they can get 'at the front of the queue' instantly.",
            "Underestimating hardware costs: HFT isn't just about code; it requires millions in specialized hardware and fiber-optic leases to compete at the top level.",
            "Ignoring 'Reg NMS' and Exchange Rules: Not understanding 'Price/Time Priority' or 'Maker-Taker' rebate structures can turn a winning strategy into a loser."
        ],
        "quiz": [
            {
                "question": "What is the primary benefit of using an FPGA in a High-Frequency Trading system?",
                "options": ["Lower power consumption", "Higher storage capacity", "Deterministic, ultra-low latency for simple logic", "Easier debugging than C++"],
                "answer": 2,
                "explanation": "FPGAs allow logic to be implemented in hardware, providing nanosecond-level processing with zero jitter (deterministic latency)."
            },
            {
                "question": "In HFT, what does 'Adverse Selection' refer to?",
                "options": ["Choosing the wrong broker", "Being filled only when the market is moving against your position", "High transaction fees", "Market makers pulling their quotes"],
                "answer": 1,
                "explanation": "Adverse selection is the risk that a market maker provides liquidity to a 'faster' informed trader who knows the price is about to change."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Trading and Exchanges — Larry Harris", "url": "https://www.amazon.com/Trading-Exchanges-Market-Microstructure-Practitioners/dp/0195144708"},
            {"icon": "📖", "name": "High-Frequency Trading — Irene Aldridge", "url": "https://www.amazon.com/High-Frequency-Trading-Practical-Algorithmic-Strategies/dp/1118343506"},
            {"icon": "🌐", "name": "Solarflare: Introduction to Kernel Bypass", "url": "https://www.xilinx.com/products/boards-and-kits/solarflare-network-adapters.html"},
            {"icon": "🌐", "name": "FIX Protocol Official Documentation", "url": "https://www.fixtrading.org/online-specification/"},
            {"icon": "🎓", "name": "QuantConnect: HFT Research Environment", "url": "https://www.quantconnect.com/"}
        ]
    },
    "Stage 10": {
        "title": "Crypto & DeFi Quantitative Methods",
        "duration": "Advanced Elective",
        "difficulty": "Expert",
        "reading_time": "50h",
        "prereqs": "Stage 3, 4, 9",
        "goal": "Apply quantitative rigor to the decentralized finance (DeFi) ecosystem and on-chain market dynamics.",
        "overview": "Crypto markets are the 24/7 wild west of finance. Unlike traditional markets, the 'order book' is often transparent on the blockchain, and 'market makers' are replaced by algorithms (AMMs). This stage teaches you how to harvest alpha from on-chain data, liquidation cascades, and decentralized liquidity pools.",
        "topics": [
            {
                "category": "On-Chain Analytics & Flow",
                "items": [
                    {"text": "Whale Tracking & Exchange Flows: Unlike equities, we can see exactly when 'Whales' move large amounts of Bitcoin to exchanges. You must learn to model 'Net Flow' to exchanges as a leading indicator of sell pressure.\n\nExample: A sudden 50,000 BTC inflow to Binance suggests a large participant is preparing to sell, often preceding a 3-5% price drop.", "is_interview_prep": True},
                    "Liquidation Heatmaps: Crypto is highly leveraged. You must learn to calculate where 'Liquidation Clusters' sit in the market. When price hits these levels, forced selling creates a 'cascade' that drives price much further than fundamentals suggest.\n\nExample: By analyzing open interest and leverage ratios, you identify a cluster of long liquidations at $60,000. If price touches $59,999, a chain reaction of selling triggers, 'gapping' the market to $58,000 in seconds."
                ]
            },
            {
                "category": "DeFi Mechanics & AMMs",
                "items": [
                    {"text": "Automated Market Makers (AMM) & Impermanent Loss: You must master the $ x \times y = k $ formula used by Uniswap. You will learn to calculate 'Imperfect Loss'—the cost of providing liquidity compared to just holding the assets.\n\nExample: You provide liquidity to an ETH/USDC pool. If ETH price doubles, you end up with more USDC and less ETH than you started with. Your 'loss' is the difference between your pool value and the value of your original assets.", "is_interview_prep": True},
                    "MEV (Maximal Extractable Value): In DeFi, the 'Miners' or 'Validators' can reorder transactions. You must understand 'Front-running,' 'Sandwich Attacks,' and 'Arbitrage' at the block level. Mastering MEV is essential for building profitable on-chain bots.\n\nExample: A bot sees a large trade pending in the 'mempool'. It pays a higher gas fee to place its own trade *before* the large one, profiting from the price impact the large trade will create."
                ]
            }
        ],
        "guide": [
            "1. Study the 'Ethereum Yellow Paper' to understand gas and EVM.",
            "2. Use Dune Analytics to build a dashboard for DEX volume.",
            "3. Learn 'Solidity' or 'Rust' for smart contract interaction."
        ],
        "exercise": "<b>The Funding Arb:</b> Research 'Basis Trading' in Crypto. Calculate the annualized return if you buy spot BTC and sell the Perps (Perpetual Futures) when funding rates are 0.01% every 8 hours.",
        "milestone": "🎯 Build a Python script that uses a WebSocket to track real-time liquidations across 3 major crypto exchanges.",
        "common_mistakes": [
            "Ignoring 'Gas' fees: In DeFi, a profitable arbitrage can be turned into a loss if you don't account for the $50-$100 cost of the transaction itself.",
            "Underestimating Smart Contract Risk: No amount of quant research can save you if the protocol you are trading on gets hacked or has a 'rug pull'.",
            "Trusting 'Oracle' prices blindly: Many DeFi protocols were exploited because their price oracles were manipulated. Always use decentralized oracles like Chainlink."
        ],
        "quiz": [
            {
                "question": "In Uniswap's constant product formula (x * y = k), what happens to the price of X as you buy more of it?",
                "options": ["It stays the same", "It decreases", "It increases exponentially", "It fluctuates randomly"],
                "answer": 2,
                "explanation": "As you remove X from the pool (buy), the ratio of Y to X increases, driving the price of X higher along a curve."
            }
        ],
        "resources": [
            {"icon": "🌐", "name": "Dune Analytics: SQL-based On-chain Data", "url": "https://dune.com/"},
            {"icon": "📖", "name": "Mastering Bitcoin — Andreas Antonopoulos", "url": "https://www.amazon.com/Mastering-Bitcoin-Programming-Open-Blockchain/dp/1491954388"},
            {"icon": "🌐", "name": "Glassnode: Crypto Market Indicators", "url": "https://glassnode.com/"}
        ]
    },
    "Stage 11": {
        "title": "Risk Management & Portfolio Oversight",
        "duration": "Advanced Capstone",
        "difficulty": "Expert",
        "reading_time": "40h",
        "prereqs": "All Previous Stages",
        "goal": "Build an institutional-grade risk management framework that ensures strategy longevity and fund survival.",
        "overview": "Risk management is not about 'avoiding' risk; it is about 'managing' it. In this capstone, you will learn the mathematical tools used by Chief Risk Officers (CROs) to ensure that a single bad day doesn't wipe out years of alpha. You will move from simple stop-losses to complex stress testing and capital allocation models.",
        "topics": [
            {
                "category": "Quantifying the Unthinkable",
                "items": [
                    {"text": "Value at Risk (VaR) vs. Expected Shortfall (CVaR): You must move beyond VaR (which only tells you the 'threshold' loss) to Expected Shortfall (which tells you the 'average' loss when that threshold is breached). CVaR is the institutional standard for managing tail risk.\n\nExample: A 95% VaR of $1M means there is a 5% chance you lose *at least* $1M. A 95% CVaR of $2.5M means that in those 5% of cases, your *average* loss is $2.5M. CVaR captures the 'severity' of the crash.", "is_interview_prep": True},
                    "Stress Testing & Scenario Analysis: A backtest is just one realization of history. You must learn to run 'What-If' scenarios: What happens to my portfolio if interest rates spike 100bps? What if 1987 happens again? Stress testing tells you where your hidden correlations lie.\n\nExample: You think your portfolio is diversified across Tech and Biotech. A 'Stress Test' shows that in a 'Rising Rate' scenario, both sectors drop 20% together, proving you weren't as hedged as you thought."
                ]
            },
            {
                "category": "Optimal Capital Allocation",
                "items": [
                    {"text": "The Kelly Criterion & Sizing for Growth: You must master the math of optimal betting. The Kelly Criterion tells you exactly how much to risk on each trade to maximize the long-term growth of your capital without hitting 'Ruin'.\n\nExample: If you have a strategy with a 60% win rate and 1:1 payoff, Kelly suggests risking 20% per trade. However, quants often use 'Fractional Kelly' (e.g., 1/4 Kelly) to buffer against model uncertainty.", "is_interview_prep": True},
                    "Risk Parity & Volatility Targeting: Institutional funds don't allocate by dollars; they allocate by 'Risk'. You will learn to use 'Volatility Targeting' to dynamically scale your position sizes so that your portfolio's risk remains constant, even as market volatility fluctuates.\n\nExample: In a calm market, you might hold $10M of exposure. If volatility doubles, you automatically cut your exposure to $5M to keep your 'Daily VaR' constant."
                ]
            }
        ],
        "guide": [
            "1. Read 'Against the Gods' by Peter Bernstein for the history of risk.",
            "2. Build a VaR/CVaR calculator in Python for your best strategy.",
            "3. Run a Monte Carlo simulation of your equity curve with varying leverage."
        ],
        "exercise": "<b>The Ruin Simulation:</b> Write a script that simulates a strategy with a 55% win rate and 1:1 payoff. Compare the equity curves of 1% risk per trade vs 10% risk per trade over 1,000 trades. Observe 'Path Dependency'.",
        "milestone": "🎯 Complete a 'Risk Audit' of your portfolio, identifying your top 3 'Tail Risk' scenarios and proposing hedges for each.",
        "common_mistakes": [
            "Treating Risk as Static: Volatility clusters. Risk often spikes exactly when your strategy is performing at its worst. Always assume correlations go to 1 during a crash.",
            "Over-reliance on Historical VaR: History doesn't always repeat. Relying solely on the last 2 years of data will leave you unprepared for a new type of regime shift.",
            "Confusing 'Diversification' with 'Safety': Buying 50 different stocks in the same sector is not diversification; it's just a concentrated bet on that sector's risk factor."
        ],
        "quiz": [
            {
                "question": "Why is Expected Shortfall (CVaR) considered superior to Value at Risk (VaR) for risk management?",
                "options": ["It is easier to calculate", "It is always a smaller number", "It accounts for the severity of losses in the 'tail' beyond the threshold", "It predicts the next crash"],
                "answer": 2,
                "explanation": "VaR only tells you the minimum loss at a certain confidence level; CVaR (Expected Shortfall) tells you the average loss in the worst-case scenarios, capturing 'tail risk' better."
            }
        ],
        "resources": [
            {"icon": "📖", "name": "Against the Gods — Peter Bernstein", "url": "https://www.amazon.com/Against-Gods-Remarkable-Story-Risk/dp/0471295639"},
            {"icon": "🎓", "name": "CFA Institute: Risk Management Overview", "url": "https://www.cfainstitute.org/en/membership/professional-development/refresher-readings/risk-management"},
            {"icon": "🌐", "name": "Risk.net: Institutional Risk News", "url": "https://www.risk.net/"}
        ]
    }
}


TRAPS = [
    {"title": "Look-ahead bias", "description": "Using future data in your signals unknowingly."},
    {"title": "Overfitting", "description": "Optimizing parameters until the backtest looks perfect."},
    {"title": "Survivorship bias", "description": "Only testing on stocks that still exist today."},
    {"title": "Ignoring costs", "description": "A 1% annual edge disappears with realistic transaction costs."},
    {"title": "Neglecting regime changes", "description": "A strategy working 2010–2020 may be dead today."}
]

TOOLS_CHECKLIST = {
    "Stage 1-2": ["Excel/Sheets", "Basic Python", "yFinance"],
    "Stage 3-4": ["Pandas", "Zipline/Backtrader", "PostgreSQL", "Git"],
    "Stage 5": ["scikit-learn", "PyTorch/TF", "QuantLib", "Interactive Brokers API"],
    "Stage 6": ["Custom execution infra", "Bloomberg/Refinitiv", "AWS/GCP", "FIX Protocol"],
    "Stage 7": ["FRED API", "TradingView/ThinkOrSwim", "Economic Calendars"],
    "Stage 8": ["OptionStat", "CBOE Tools", "Greeks Calculators", "QuantLib (C++/Python)"],
    "Stage 9": ["C++ (Modern C++20)", "Solarflare OpenOnload", "FIX/SBE Engines", "FPGA Dev Kits"],
    "Stage 10": ["Dune Analytics", "Ethers.js / Web3.py", "Solidity/Rust", "MetaMask/Hardware Wallets"],
    "Stage 11": ["RiskMetrics", "Monte Carlo Simulators", "GARCH Modeling (arch library)", "VaR/CVaR Engines"]
}
